# Generated by Django 5.2.6 on 2025-10-15 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faq_id', models.CharField(blank=True, default='', editable=False, max_length=32, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(db_index=True, default=0, unique=True)),
                ('is_schema_ready', models.BooleanField(default=True)),
                ('thumbs_up', models.PositiveIntegerField(blank=True, default=0, help_text='Number of thumbs up votes')),
                ('thumbs_down', models.PositiveIntegerField(blank=True, default=0, help_text='Number of thumbs down votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_event_id', models.CharField(blank=True, default='', editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('content_type', models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event Announcement'), ('ANNOUNCEMENT', 'General Announcement')], db_index=True, default='NEWS', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_event_covers/')),
                ('cover_image_blob', models.BinaryField(blank=True, null=True)),
                ('cover_image_blob_mime', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cover_image_blob_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Or provide a URL for the cover image.', max_length=500)),
                ('external_link', models.URLField(blank=True, help_text='Optional link if the news is hosted elsewhere.', max_length=500)),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News/Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, default='', editable=False, max_length=32, unique=True)),
                ('kicc_project_id', models.CharField(blank=True, help_text='The ID of the project in the External Service API (KICC).', max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('teaser', models.TextField()),
                ('background_objectives', models.TextField()),
                ('tasks_eligibility', models.TextField()),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('theme', models.CharField(db_index=True, help_text='Hot categories (e.g., Education, Medical).', max_length=100)),
                ('duration', models.IntegerField(db_index=True, help_text='Estimated total hours.')),
                ('difficulty', models.CharField(blank=True, db_index=True, max_length=50)),
                ('headcount', models.IntegerField(blank=True, default=0, help_text='Current number of volunteers signed up.', null=True)),
                ('total_headcount', models.IntegerField(default=0, help_text='Maximum allowed headcount for the project.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='project_covers/')),
                ('cover_image_blob', models.BinaryField(blank=True, null=True)),
                ('cover_image_blob_mime', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cover_image_blob_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Or provide a URL for the cover image.', max_length=500, null=True)),
                ('application_deadline', models.DateTimeField(db_index=True)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hero_highlight', models.BooleanField(default=False, help_text='For Hero Carousel (FR-1.2).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('success_story_id', models.CharField(blank=True, default='', editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='success_story_covers/')),
                ('cover_image_blob', models.BinaryField(blank=True, null=True)),
                ('cover_image_blob_mime', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cover_image_blob_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Or provide a URL for the cover image.', max_length=500, null=True)),
                ('image_file', models.ImageField(blank=True, help_text='Upload an image.', null=True, upload_to='success_story_images/')),
                ('image_file_blob', models.BinaryField(blank=True, null=True)),
                ('image_file_blob_mime', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image_file_blob_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list, help_text='List of image URLs for the media gallery.')),
                ('video_urls', models.JSONField(blank=True, default=list, help_text='List of video URLs for the media gallery.')),
                ('beneficiaries', models.IntegerField(blank=True, null=True)),
                ('total_hours_contributed', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'ordering': ['-published_at'],
            },
        ),
    ]
