# Generated by Django 5.2.6 on 2025-10-15 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successstory',
            name='related_project',
            field=models.ForeignKey(blank=True, help_text='The volunteer project this story is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='content.project'),
        ),
    ]
