# Generated by Django 5.2.6 on 2025-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='is_hero_highlight',
            field=models.BooleanField(default=False, help_text='For Hero Carousel display.'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_hero_highlight',
            field=models.BooleanField(default=False, help_text='For Hero Carousel display.'),
        ),
    ]
