# Generated by Django 5.2.6 on 2025-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_newsevent_is_hero_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured news/events appear in prominent positions across the site.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured projects appear in prominent positions across the site.'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured success stories appear in prominent positions across the site.'),
        ),
    ]
