# Generated by Django 5.2.6 on 2025-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_newsevent_is_featured_project_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, help_text='Difficulty level of the project.', max_length=50),
        ),
    ]
