# Generated by Django 5.2.6 on 2025-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_project_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, help_text='Difficulty level of the project.', max_length=50),
        ),
    ]
