# Generated by Django 5.2.6 on 2025-11-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_project_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='image_file_blob',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='image_file_blob_mime',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='image_file_blob_name',
        ),
        migrations.CreateModel(
            name='SuccessStoryGalleryImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_blob', models.BinaryField(help_text='Image data stored as binary.')),
                ('image_blob_mime', models.CharField(help_text='MIME type of the image (e.g., image/jpeg, image/png).', max_length=255)),
                ('image_blob_name', models.CharField(help_text='Original filename of the uploaded image.', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional caption or description for this image.', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order for the gallery images.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_story', models.ForeignKey(help_text='The success story this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.successstory')),
            ],
            options={
                'verbose_name': 'Success Story Gallery Image',
                'verbose_name_plural': 'Success Story Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
