# Generated by Django 5.2.6 on 2025-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_project_video_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='video_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of video URLs (YouTube, Vimeo, etc.) for the media gallery.'),
        ),
    ]
