# Generated by Django 5.2.6 on 2025-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_news_event_video_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_zh_tw',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='body_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='title_zh_tw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='background_objectives_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='background_objectives_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_eligibility_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_eligibility_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='teaser_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='teaser_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_zh_tw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='body_zh_tw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='successstory',
            name='title_zh_tw',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
