# Generated by Django 5.2.6 on 2025-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_faq_answer_en_faq_answer_zh_tw_faq_question_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country_en',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country_zh_tw',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='theme_en',
            field=models.CharField(db_index=True, help_text='Hot categories (e.g., Education, Medical).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='theme_zh_tw',
            field=models.CharField(db_index=True, help_text='Hot categories (e.g., Education, Medical).', max_length=100, null=True),
        ),
    ]
