# Generated by Django 5.2.6 on 2025-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_faq_created_at_alter_newsevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for the media gallery.'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for the media gallery.'),
        ),
    ]
