# Generated by Django 5.2.6 on 2025-12-11 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_newsevent_image_urls_project_image_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UP', 'Thumbs Up'), ('DOWN', 'Thumbs Down')], help_text='Type of vote: up or down.', max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ Vote',
                'verbose_name_plural': 'FAQ Votes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'faq')},
            },
        ),
    ]
