from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import date, timedelta
import random
from apps.users.models import CustomUser
from apps.content.models import Project, NewsEvent, SuccessStory, FAQ


class Command(BaseCommand):
    help = 'Seed the database with sample data with theme-specific images'

    def handle(self, *args, **options):
        self.stdout.write('Seeding database...')
        self.create_users()
        self.create_projects()
        self.create_news_events()
        self.create_success_stories()
        self.create_faqs()
        self.stdout.write(self.style.SUCCESS('Database seeded successfully!'))

    def create_users(self):
        users_data = [
            {'username': 'john_doe', 'email': 'john@example.com', 'first_name': 'John', 'last_name': 'Doe', 'date_of_birth': date(1990, 5, 15), 'gender': 'Male', 'blood_group': 'O+', 'guardian_name': 'Jane Doe', 'guardian_relation': 'Mother', 'address': '123 Main St, New York, USA', 'contact': '1234567890', 'country_code': '+1'},
            {'username': 'jane_smith', 'email': 'jane@example.com', 'first_name': 'Jane', 'last_name': 'Smith', 'date_of_birth': date(1985, 8, 20), 'gender': 'Female', 'blood_group': 'A+', 'guardian_name': 'Bob Smith', 'guardian_relation': 'Father', 'address': '456 Oak Ave, Los Angeles, USA', 'contact': '0987654321', 'country_code': '+1'},
            {'username': 'rajesh_kumar', 'email': 'rajesh@example.com', 'first_name': 'Rajesh', 'last_name': 'Kumar', 'date_of_birth': date(1992, 3, 10), 'gender': 'Male', 'blood_group': 'B+', 'guardian_name': 'Priya Kumar', 'guardian_relation': 'Mother', 'address': '789 Gandhi Marg, Mumbai, India', 'contact': '9876543210', 'country_code': '+91'},
            {'username': 'priya_verma', 'email': 'priya@example.com', 'first_name': 'Priya', 'last_name': 'Verma', 'date_of_birth': date(1988, 11, 25), 'gender': 'Female', 'blood_group': 'AB+', 'guardian_name': 'Amit Verma', 'guardian_relation': 'Father', 'address': '321 Delhi Road, Delhi, India', 'contact': '8765432109', 'country_code': '+91'},
            {'username': 'michael_johnson', 'email': 'michael@example.com', 'first_name': 'Michael', 'last_name': 'Johnson', 'date_of_birth': date(1995, 7, 14), 'gender': 'Male', 'blood_group': 'O-', 'guardian_name': 'Sarah Johnson', 'guardian_relation': 'Mother', 'address': '654 Spring Lane, Chicago, USA', 'contact': '5555555555', 'country_code': '+1'},
            {'username': 'emma_wilson', 'email': 'emma@example.com', 'first_name': 'Emma', 'last_name': 'Wilson', 'date_of_birth': date(1993, 2, 8), 'gender': 'Female', 'blood_group': 'B-', 'guardian_name': 'David Wilson', 'guardian_relation': 'Father', 'address': '987 Maple Ave, Toronto, Canada', 'contact': '4165551234', 'country_code': '+1'},
            {'username': 'arun_patel', 'email': 'arun@example.com', 'first_name': 'Arun', 'last_name': 'Patel', 'date_of_birth': date(1991, 6, 22), 'gender': 'Male', 'blood_group': 'A-', 'guardian_name': 'Neha Patel', 'guardian_relation': 'Wife', 'address': '432 Park Street, Bangalore, India', 'contact': '8888888888', 'country_code': '+91'},
            {'username': 'sophia_chen', 'email': 'sophia@example.com', 'first_name': 'Sophia', 'last_name': 'Chen', 'date_of_birth': date(1994, 9, 3), 'gender': 'Female', 'blood_group': 'O+', 'guardian_name': 'Wei Chen', 'guardian_relation': 'Father', 'address': '555 Dragon Lane, Singapore', 'contact': '6587654321', 'country_code': '+65'},
            {'username': 'marcus_brown', 'email': 'marcus@example.com', 'first_name': 'Marcus', 'last_name': 'Brown', 'date_of_birth': date(1989, 12, 30), 'gender': 'Male', 'blood_group': 'B+', 'guardian_name': 'Patricia Brown', 'guardian_relation': 'Mother', 'address': '777 Oak Drive, Atlanta, USA', 'contact': '4045551111', 'country_code': '+1'},
            {'username': 'linda_garcia', 'email': 'linda@example.com', 'first_name': 'Linda', 'last_name': 'Garcia', 'date_of_birth': date(1987, 4, 17), 'gender': 'Female', 'blood_group': 'AB-', 'guardian_name': 'Carlos Garcia', 'guardian_relation': 'Father', 'address': '888 Sunset Blvd, Los Angeles, USA', 'contact': '2135559999', 'country_code': '+1'},
            {'username': 'vikram_singh', 'email': 'vikram@example.com', 'first_name': 'Vikram', 'last_name': 'Singh', 'date_of_birth': date(1996, 1, 12), 'gender': 'Male', 'blood_group': 'O-', 'guardian_name': 'Sunita Singh', 'guardian_relation': 'Mother', 'address': '999 Raj Path, New Delhi, India', 'contact': '9999999999', 'country_code': '+91'},
            {'username': 'jessica_lee', 'email': 'jessica@example.com', 'first_name': 'Jessica', 'last_name': 'Lee', 'date_of_birth': date(1991, 7, 25), 'gender': 'Female', 'blood_group': 'A+', 'guardian_name': 'James Lee', 'guardian_relation': 'Father', 'address': '444 Oak Street, Seattle, USA', 'contact': '2065551234', 'country_code': '+1'},
            {'username': 'sameer_ahmed', 'email': 'sameer@example.com', 'first_name': 'Sameer', 'last_name': 'Ahmed', 'date_of_birth': date(1993, 10, 8), 'gender': 'Male', 'blood_group': 'B-', 'guardian_name': 'Fatima Ahmed', 'guardian_relation': 'Mother', 'address': '333 Khan Street, Karachi, Pakistan', 'contact': '3335554444', 'country_code': '+92'},
            {'username': 'maya_patel', 'email': 'maya@example.com', 'first_name': 'Maya', 'last_name': 'Patel', 'date_of_birth': date(1990, 11, 14), 'gender': 'Female', 'blood_group': 'AB+', 'guardian_name': 'Rajesh Patel', 'guardian_relation': 'Father', 'address': '111 Fortune Street, Ahmedabad, India', 'contact': '7777777777', 'country_code': '+91'},
            {'username': 'david_miller', 'email': 'david@example.com', 'first_name': 'David', 'last_name': 'Miller', 'date_of_birth': date(1988, 3, 29), 'gender': 'Male', 'blood_group': 'O+', 'guardian_name': 'Susan Miller', 'guardian_relation': 'Mother', 'address': '222 Elm Street, Boston, USA', 'contact': '6175551234', 'country_code': '+1'},
            {'username': 'isha_menon', 'email': 'isha@example.com', 'first_name': 'Isha', 'last_name': 'Menon', 'date_of_birth': date(1994, 5, 6), 'gender': 'Female', 'blood_group': 'A-', 'guardian_name': 'Anand Menon', 'guardian_relation': 'Father', 'address': '555 Temple Road, Kochi, India', 'contact': '9876543211', 'country_code': '+91'},
            {'username': 'ivan_volkov', 'email': 'ivan@example.com', 'first_name': 'Ivan', 'last_name': 'Volkov', 'date_of_birth': date(1992, 8, 18), 'gender': 'Male', 'blood_group': 'B+', 'guardian_name': 'Natasha Volkov', 'guardian_relation': 'Mother', 'address': '666 Moscow Street, Moscow, Russia', 'contact': '79991234567', 'country_code': '+7'},
            {'username': 'natalia_koval', 'email': 'natalia@example.com', 'first_name': 'Natalia', 'last_name': 'Koval', 'date_of_birth': date(1989, 2, 11), 'gender': 'Female', 'blood_group': 'O-', 'guardian_name': 'Dmitri Koval', 'guardian_relation': 'Father', 'address': '777 Kiev Street, Kiev, Ukraine', 'contact': '380501234567', 'country_code': '+380'},
            {'username': 'pablo_santos', 'email': 'pablo@example.com', 'first_name': 'Pablo', 'last_name': 'Santos', 'date_of_birth': date(1991, 9, 7), 'gender': 'Male', 'blood_group': 'AB+', 'guardian_name': 'Maria Santos', 'guardian_relation': 'Mother', 'address': '888 El Camino, Mexico City, Mexico', 'contact': '525512345678', 'country_code': '+52'},
            {'username': 'carolina_silva', 'email': 'carolina@example.com', 'first_name': 'Carolina', 'last_name': 'Silva', 'date_of_birth': date(1993, 6, 19), 'gender': 'Female', 'blood_group': 'A+', 'guardian_name': 'Fernando Silva', 'guardian_relation': 'Father', 'address': '999 Rio Street, Rio de Janeiro, Brazil', 'contact': '85987654321', 'country_code': '+55'},
            {'username': 'yuki_tanaka', 'email': 'yuki@example.com', 'first_name': 'Yuki', 'last_name': 'Tanaka', 'date_of_birth': date(1990, 4, 23), 'gender': 'Female', 'blood_group': 'B-', 'guardian_name': 'Hideo Tanaka', 'guardian_relation': 'Father', 'address': '111 Tokyo Street, Tokyo, Japan', 'contact': '9012345678', 'country_code': '+81'},
            {'username': 'kenji_nakamura', 'email': 'kenji@example.com', 'first_name': 'Kenji', 'last_name': 'Nakamura', 'date_of_birth': date(1995, 10, 2), 'gender': 'Male', 'blood_group': 'O+', 'guardian_name': 'Yoko Nakamura', 'guardian_relation': 'Mother', 'address': '222 Osaka Street, Osaka, Japan', 'contact': '9087654321', 'country_code': '+81'},
            {'username': 'anna_larsson', 'email': 'anna@example.com', 'first_name': 'Anna', 'last_name': 'Larsson', 'date_of_birth': date(1992, 7, 14), 'gender': 'Female', 'blood_group': 'AB-', 'guardian_name': 'Erik Larsson', 'guardian_relation': 'Father', 'address': '333 Stockholm Street, Stockholm, Sweden', 'contact': '46701234567', 'country_code': '+46'},
            {'username': 'lars_andersson', 'email': 'lars@example.com', 'first_name': 'Lars', 'last_name': 'Andersson', 'date_of_birth': date(1988, 12, 5), 'gender': 'Male', 'blood_group': 'A+', 'guardian_name': 'Ingrid Andersson', 'guardian_relation': 'Mother', 'address': '444 Gothenburg Street, Gothenburg, Sweden', 'contact': '46801234567', 'country_code': '+46'},
            {'username': 'sophie_dubois', 'email': 'sophie@example.com', 'first_name': 'Sophie', 'last_name': 'Dubois', 'date_of_birth': date(1994, 1, 28), 'gender': 'Female', 'blood_group': 'O-', 'guardian_name': 'Pierre Dubois', 'guardian_relation': 'Father', 'address': '555 Paris Street, Paris, France', 'contact': '33612345678', 'country_code': '+33'},
            {'username': 'pierre_martin', 'email': 'pierre@example.com', 'first_name': 'Pierre', 'last_name': 'Martin', 'date_of_birth': date(1989, 5, 16), 'gender': 'Male', 'blood_group': 'B+', 'guardian_name': 'Marie Martin', 'guardian_relation': 'Mother', 'address': '666 Lyon Street, Lyon, France', 'contact': '33712345678', 'country_code': '+33'},
            {'username': 'klaus_mueller', 'email': 'klaus@example.com', 'first_name': 'Klaus', 'last_name': 'Mueller', 'date_of_birth': date(1991, 8, 9), 'gender': 'Male', 'blood_group': 'A-', 'guardian_name': 'Greta Mueller', 'guardian_relation': 'Mother', 'address': '777 Berlin Street, Berlin, Germany', 'contact': '49301234567', 'country_code': '+49'},
            {'username': 'angela_fischer', 'email': 'angela@example.com', 'first_name': 'Angela', 'last_name': 'Fischer', 'date_of_birth': date(1993, 11, 22), 'gender': 'Female', 'blood_group': 'AB+', 'guardian_name': 'Hans Fischer', 'guardian_relation': 'Father', 'address': '888 Munich Street, Munich, Germany', 'contact': '49891234567', 'country_code': '+49'},
        ]

        for user_data in users_data:
            user, created = CustomUser.objects.get_or_create(username=user_data['username'], defaults=user_data)
            if created:
                user.set_password('password123')
                user.save()
                self.stdout.write(f'Created user: {user.username}')
            else:
                self.stdout.write(f'User {user.username} already exists')

    def create_projects(self):
        projects_data = [
            # EDUCATION PROJECTS
            {'kicc_project_id': 'KICC001', 'title': 'Community Education Program', 'teaser': 'Help educate underprivileged children in rural areas.', 'background_objectives': 'Improve literacy rates and provide computer science education to rural youth.', 'tasks_eligibility': 'Teaching experience preferred. English communication skills required.', 'country': 'India', 'theme': 'Education', 'duration': 480, 'difficulty': 'Medium', 'headcount': 5, 'total_headcount': 10, 'application_deadline': timezone.now() + timedelta(days=30), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/community,education'},
            {'kicc_project_id': 'KICC018', 'title': 'Language & Cultural Exchange Program', 'teaser': 'Teach languages and share cultural knowledge.', 'background_objectives': 'Bridge cultural gaps through language and education.', 'tasks_eligibility': 'Fluency in target language required. Cultural sensitivity essential.', 'country': 'Japan', 'theme': 'Education', 'duration': 360, 'difficulty': 'Medium', 'headcount': 5, 'total_headcount': 10, 'application_deadline': timezone.now() + timedelta(days=32), 'start_date': date.today() + timedelta(days=62), 'end_date': date.today() + timedelta(days=242), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/language,culture'},
            {'kicc_project_id': 'KICC024', 'title': 'Tech Skills for Underprivileged Youth', 'teaser': 'Teach technology and coding to underprivileged youth.', 'background_objectives': 'Provide tech skills to increase employment opportunities.', 'tasks_eligibility': 'Programming or technology background required.', 'country': 'India', 'theme': 'Education', 'duration': 360, 'difficulty': 'Medium', 'headcount': 6, 'total_headcount': 12, 'application_deadline': timezone.now() + timedelta(days=32), 'start_date': date.today() + timedelta(days=62), 'end_date': date.today() + timedelta(days=242), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/technology,coding'},
            {'kicc_project_id': 'KICC026', 'title': 'School Construction & Renovation', 'teaser': 'Build and renovate schools in underserved areas.', 'background_objectives': 'Improve educational infrastructure in rural areas.', 'tasks_eligibility': 'Construction or engineering background preferred.', 'country': 'Myanmar', 'theme': 'Education', 'duration': 180, 'difficulty': 'Hard', 'headcount': 12, 'total_headcount': 25, 'application_deadline': timezone.now() + timedelta(days=40), 'start_date': date.today() + timedelta(days=70), 'end_date': date.today() + timedelta(days=250), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/construction,school'},
            {'kicc_project_id': 'KICC027', 'title': 'Community Library Establishment', 'teaser': 'Establish and manage community libraries.', 'background_objectives': 'Promote literacy and knowledge through community libraries.', 'tasks_eligibility': 'Library science background or passion for books.', 'country': 'India', 'theme': 'Education', 'duration': 360, 'difficulty': 'Easy', 'headcount': 5, 'total_headcount': 10, 'application_deadline': timezone.now() + timedelta(days=25), 'start_date': date.today() + timedelta(days=55), 'end_date': date.today() + timedelta(days=235), 'is_active': False, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/library,books'},
            # HEALTHCARE PROJECTS
            {'kicc_project_id': 'KICC002', 'title': 'Healthcare Outreach Initiative', 'teaser': 'Support medical camps in underserved communities.', 'background_objectives': 'Provide basic healthcare services and health awareness to remote villages.', 'tasks_eligibility': 'Medical background or health awareness training preferred. Compassion required.', 'country': 'India', 'theme': 'Healthcare', 'duration': 360, 'difficulty': 'Hard', 'headcount': 8, 'total_headcount': 15, 'application_deadline': timezone.now() + timedelta(days=45), 'start_date': date.today() + timedelta(days=75), 'end_date': date.today() + timedelta(days=210), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/healthcare,medical'},
            {'kicc_project_id': 'KICC007', 'title': 'Child Nutrition Program', 'teaser': 'Provide nutritious meals to malnourished children.', 'background_objectives': 'Combat child malnutrition and improve health outcomes.', 'tasks_eligibility': 'Nutrition knowledge preferred. Compassion essential.', 'country': 'India', 'theme': 'Health & Nutrition', 'duration': 360, 'difficulty': 'Medium', 'headcount': 8, 'total_headcount': 16, 'application_deadline': timezone.now() + timedelta(days=28), 'start_date': date.today() + timedelta(days=50), 'end_date': date.today() + timedelta(days=230), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,nutrition'},
            {'kicc_project_id': 'KICC015', 'title': 'HIV/AIDS Awareness Program', 'teaser': 'Provide HIV/AIDS education and support services.', 'background_objectives': 'Combat stigma and provide awareness about HIV/AIDS prevention.', 'tasks_eligibility': 'Health awareness and sensitivity essential.', 'country': 'South Africa', 'theme': 'Health Awareness', 'duration': 360, 'difficulty': 'Medium', 'headcount': 7, 'total_headcount': 14, 'application_deadline': timezone.now() + timedelta(days=28), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/health,awareness'},
            {'kicc_project_id': 'KICC021', 'title': 'Community Health Centers Establishment', 'teaser': 'Establish and operate primary healthcare centers.', 'background_objectives': 'Provide basic healthcare infrastructure to underserved areas.', 'tasks_eligibility': 'Medical or healthcare administration experience required.', 'country': 'Nigeria', 'theme': 'Healthcare', 'duration': 480, 'difficulty': 'Hard', 'headcount': 10, 'total_headcount': 20, 'application_deadline': timezone.now() + timedelta(days=40), 'start_date': date.today() + timedelta(days=70), 'end_date': date.today() + timedelta(days=270), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/health,center'},
            # ENVIRONMENT PROJECTS
            {'kicc_project_id': 'KICC003', 'title': 'Environmental Conservation Project', 'teaser': 'Join us in planting trees and protecting wildlife habitats.', 'background_objectives': 'Combat deforestation and promote environmental awareness in local communities.', 'tasks_eligibility': 'Passion for environment. No specific qualifications needed.', 'country': 'Kenya', 'theme': 'Environment', 'duration': 240, 'difficulty': 'Easy', 'headcount': 10, 'total_headcount': 20, 'application_deadline': timezone.now() + timedelta(days=20), 'start_date': date.today() + timedelta(days=45), 'end_date': date.today() + timedelta(days=285), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/environment,conservation'},
            {'kicc_project_id': 'KICC008', 'title': 'Rural Water & Sanitation Project', 'teaser': 'Build sustainable water and sanitation facilities in rural areas.', 'background_objectives': 'Ensure access to clean water and proper sanitation in villages.', 'tasks_eligibility': 'Engineering or construction background helpful. Problem-solving skills needed.', 'country': 'Uganda', 'theme': 'Water & Sanitation', 'duration': 300, 'difficulty': 'Hard', 'headcount': 10, 'total_headcount': 20, 'application_deadline': timezone.now() + timedelta(days=40), 'start_date': date.today() + timedelta(days=70), 'end_date': date.today() + timedelta(days=270), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/water,sanitation'},
            {'kicc_project_id': 'KICC013', 'title': 'Environmental Cleanup Drive', 'teaser': 'Clean and restore local ecosystems and water bodies.', 'background_objectives': 'Remove pollution and restore natural habitats.', 'tasks_eligibility': 'Physical fitness and environmental passion required.', 'country': 'Philippines', 'theme': 'Environment', 'duration': 180, 'difficulty': 'Easy', 'headcount': 15, 'total_headcount': 30, 'application_deadline': timezone.now() + timedelta(days=20), 'start_date': date.today() + timedelta(days=40), 'end_date': date.today() + timedelta(days=220), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/environment,cleanup'},
            {'kicc_project_id': 'KICC014', 'title': 'Agricultural Development Project', 'teaser': 'Improve farming practices and agricultural productivity.', 'background_objectives': 'Teach sustainable farming methods and increase crop yields.', 'tasks_eligibility': 'Agriculture or farming background preferred. Problem-solving skills needed.', 'country': 'Ethiopia', 'theme': 'Agriculture', 'duration': 300, 'difficulty': 'Medium', 'headcount': 6, 'total_headcount': 12, 'application_deadline': timezone.now() + timedelta(days=35), 'start_date': date.today() + timedelta(days=65), 'end_date': date.today() + timedelta(days=245), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/agriculture,farming'},
            {'kicc_project_id': 'KICC020', 'title': 'Renewable Energy Education', 'teaser': 'Teach renewable energy solutions to communities.', 'background_objectives': 'Promote sustainable energy and environmental awareness.', 'tasks_eligibility': 'Engineering or sustainability background helpful.', 'country': 'India', 'theme': 'Environment', 'duration': 300, 'difficulty': 'Hard', 'headcount': 5, 'total_headcount': 10, 'application_deadline': timezone.now() + timedelta(days=30), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/renewable,energy'},
            # WOMEN EMPOWERMENT PROJECTS
            {'kicc_project_id': 'KICC004', 'title': 'Women Empowerment & Skill Development', 'teaser': 'Empower women through vocational training and entrepreneurship programs.', 'background_objectives': 'Provide skills training to help women achieve economic independence.', 'tasks_eligibility': 'Experience in training or mentoring. Gender sensitivity required.', 'country': 'India', 'theme': 'Women Empowerment', 'duration': 360, 'difficulty': 'Medium', 'headcount': 6, 'total_headcount': 12, 'application_deadline': timezone.now() + timedelta(days=35), 'start_date': date.today() + timedelta(days=65), 'end_date': date.today() + timedelta(days=215), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/women,empowerment'},
            {'kicc_project_id': 'KICC010', 'title': 'Community Microfinance Initiative', 'teaser': 'Support women entrepreneurs through microfinance programs.', 'background_objectives': 'Provide financial literacy and microloans to women entrepreneurs.', 'tasks_eligibility': 'Finance or business background. Entrepreneurship knowledge needed.', 'country': 'India', 'theme': 'Economic Empowerment', 'duration': 360, 'difficulty': 'Medium', 'headcount': 5, 'total_headcount': 10, 'application_deadline': timezone.now() + timedelta(days=38), 'start_date': date.today() + timedelta(days=65), 'end_date': date.today() + timedelta(days=245), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/microfinance,business'},
            {'kicc_project_id': 'KICC023', 'title': 'Gender Equality & Women Rights Advocacy', 'teaser': 'Advocate for gender equality and women rights.', 'background_objectives': 'Promote gender equality and combat discrimination.', 'tasks_eligibility': 'Social advocacy background preferred. Passion for equality essential.', 'country': 'India', 'theme': 'Gender Equality', 'duration': 300, 'difficulty': 'Medium', 'headcount': 7, 'total_headcount': 14, 'application_deadline': timezone.now() + timedelta(days=28), 'start_date': date.today() + timedelta(days=58), 'end_date': date.today() + timedelta(days=238), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/gender,equality'},
            # DISASTER RELIEF PROJECTS
            {'kicc_project_id': 'KICC005', 'title': 'Disaster Relief & Rehabilitation', 'teaser': 'Help affected communities recover from natural disasters.', 'background_objectives': 'Provide relief supplies, temporary shelter, and rehabilitation support.', 'tasks_eligibility': 'Physical fitness important. Emotional resilience needed.', 'country': 'Bangladesh', 'theme': 'Disaster Relief', 'duration': 180, 'difficulty': 'Hard', 'headcount': 12, 'total_headcount': 25, 'application_deadline': timezone.now() + timedelta(days=15), 'start_date': date.today() + timedelta(days=30), 'end_date': date.today() + timedelta(days=210), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/disaster,relief'},
            {'kicc_project_id': 'KICC025', 'title': 'Community Disaster Preparedness', 'teaser': 'Train communities for disaster preparedness and response.', 'background_objectives': 'Build disaster preparedness and emergency response capabilities.', 'tasks_eligibility': 'Emergency management experience helpful. Leadership skills needed.', 'country': 'Philippines', 'theme': 'Disaster Management', 'duration': 240, 'difficulty': 'Medium', 'headcount': 8, 'total_headcount': 16, 'application_deadline': timezone.now() + timedelta(days=30), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/disaster,preparedness'},
            # DIGITAL LITERACY
            {'kicc_project_id': 'KICC006', 'title': 'Digital Literacy for Seniors', 'teaser': 'Teach basic digital skills to elderly community members.', 'background_objectives': 'Bridge the digital divide and help seniors stay connected with technology.', 'tasks_eligibility': 'Patience and good communication skills. Tech knowledge required.', 'country': 'Australia', 'theme': 'Digital Literacy', 'duration': 300, 'difficulty': 'Easy', 'headcount': 7, 'total_headcount': 14, 'application_deadline': timezone.now() + timedelta(days=25), 'start_date': date.today() + timedelta(days=55), 'end_date': date.today() + timedelta(days=235), 'is_active': False, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/digital,literacy'},
            # MENTAL HEALTH
            {'kicc_project_id': 'KICC011', 'title': 'Mental Health Awareness Campaign', 'teaser': 'Promote mental health awareness in underserved communities.', 'background_objectives': 'Break stigma around mental health and provide awareness programs.', 'tasks_eligibility': 'Psychology background helpful. Good communication skills required.', 'country': 'Sri Lanka', 'theme': 'Mental Health', 'duration': 240, 'difficulty': 'Medium', 'headcount': 7, 'total_headcount': 14, 'application_deadline': timezone.now() + timedelta(days=25), 'start_date': date.today() + timedelta(days=55), 'end_date': date.today() + timedelta(days=235), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/mental,health'},
            # SKILLS TRAINING
            {'kicc_project_id': 'KICC012', 'title': 'Artisan Skills Training Program', 'teaser': 'Teach traditional and modern skills to artisans.', 'background_objectives': 'Preserve traditional arts while enhancing marketable skills.', 'tasks_eligibility': 'Artistic background or craftsmanship experience preferred.', 'country': 'India', 'theme': 'Skills Training', 'duration': 360, 'difficulty': 'Easy', 'headcount': 8, 'total_headcount': 16, 'application_deadline': timezone.now() + timedelta(days=30), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/artisan,skills'},
            # CHILD WELFARE
            {'kicc_project_id': 'KICC009', 'title': 'Street Children Rehabilitation Program', 'teaser': 'Rehabilitate and educate street children.', 'background_objectives': 'Provide shelter, education, and skill training to street children.', 'tasks_eligibility': 'Patience and empathy crucial. Previous experience with vulnerable groups preferred.', 'country': 'India', 'theme': 'Child Welfare', 'duration': 480, 'difficulty': 'Hard', 'headcount': 6, 'total_headcount': 12, 'application_deadline': timezone.now() + timedelta(days=32), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,welfare'},
            {'kicc_project_id': 'KICC028', 'title': 'Child Protection & Trafficking Prevention', 'teaser': 'Protect children from exploitation and trafficking.', 'background_objectives': 'Prevent child trafficking and provide protection services.', 'tasks_eligibility': 'Child protection background preferred. Empathy essential.', 'country': 'India', 'theme': 'Child Welfare', 'duration': 480, 'difficulty': 'Hard', 'headcount': 7, 'total_headcount': 14, 'application_deadline': timezone.now() + timedelta(days=35), 'start_date': date.today() + timedelta(days=65), 'end_date': date.today() + timedelta(days=245), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,protection'},
            # ELDERLY CARE
            {'kicc_project_id': 'KICC017', 'title': 'Elderly Care Support Program', 'teaser': 'Provide care and companionship to elderly people.', 'background_objectives': 'Improve quality of life for elderly in care homes and communities.', 'tasks_eligibility': 'Patience and empathy essential. Caregiving experience helpful.', 'country': 'USA', 'theme': 'Elderly Care', 'duration': 180, 'difficulty': 'Easy', 'headcount': 10, 'total_headcount': 20, 'application_deadline': timezone.now() + timedelta(days=20), 'start_date': date.today() + timedelta(days=45), 'end_date': date.today() + timedelta(days=225), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/elderly,care'},
            # ANIMAL WELFARE
            {'kicc_project_id': 'KICC019', 'title': 'Animal Welfare & Veterinary Support', 'teaser': 'Provide veterinary care to animals in need.', 'background_objectives': 'Improve animal welfare and provide free veterinary services.', 'tasks_eligibility': 'Veterinary background or animal care experience preferred.', 'country': 'India', 'theme': 'Animal Welfare', 'duration': 240, 'difficulty': 'Medium', 'headcount': 6, 'total_headcount': 12, 'application_deadline': timezone.now() + timedelta(days=27), 'start_date': date.today() + timedelta(days=57), 'end_date': date.today() + timedelta(days=237), 'is_active': False, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/animal,welfare'},
            # REFUGEE SUPPORT
            {'kicc_project_id': 'KICC022', 'title': 'Refugee Support & Integration Program', 'teaser': 'Help refugees integrate into new communities.', 'background_objectives': 'Provide support services and integration assistance to refugees.', 'tasks_eligibility': 'Cultural sensitivity and empathy essential. Language skills helpful.', 'country': 'Germany', 'theme': 'Refugee Support', 'duration': 360, 'difficulty': 'Hard', 'headcount': 8, 'total_headcount': 16, 'application_deadline': timezone.now() + timedelta(days=35), 'start_date': date.today() + timedelta(days=65), 'end_date': date.today() + timedelta(days=245), 'is_active': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/refugee,support'},
            # YOUTH DEVELOPMENT
            {'kicc_project_id': 'KICC016', 'title': 'Sports Development Initiative', 'teaser': 'Use sports to develop underprivileged youth.', 'background_objectives': 'Build character and fitness through sports programs.', 'tasks_eligibility': 'Sports background or coaching experience preferred.', 'country': 'India', 'theme': 'Youth Development', 'duration': 240, 'difficulty': 'Easy', 'headcount': 8, 'total_headcount': 16, 'application_deadline': timezone.now() + timedelta(days=25), 'start_date': date.today() + timedelta(days=50), 'end_date': date.today() + timedelta(days=230), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/youth,sports'},
            {'kicc_project_id': 'KICC030', 'title': 'Community Sports & Recreation Facility', 'teaser': 'Create recreational facilities for community youth.', 'background_objectives': 'Build sports facilities and promote youth engagement.', 'tasks_eligibility': 'Sports or recreation management background helpful.', 'country': 'India', 'theme': 'Youth Development', 'duration': 240, 'difficulty': 'Easy', 'headcount': 8, 'total_headcount': 16, 'application_deadline': timezone.now() + timedelta(days=28), 'start_date': date.today() + timedelta(days=58), 'end_date': date.today() + timedelta(days=238), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/sports,facility'},
            # ECONOMIC DEVELOPMENT
            {'kicc_project_id': 'KICC029', 'title': 'Community Microenterprise Support', 'teaser': 'Support community members in starting microenterprises.', 'background_objectives': 'Build economic independence through business support.', 'tasks_eligibility': 'Business mentoring or entrepreneurship experience helpful.', 'country': 'India', 'theme': 'Economic Development', 'duration': 300, 'difficulty': 'Medium', 'headcount': 6, 'total_headcount': 12, 'application_deadline': timezone.now() + timedelta(days=30), 'start_date': date.today() + timedelta(days=60), 'end_date': date.today() + timedelta(days=240), 'is_active': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/microenterprise,business'},
        ]

        for project_data in projects_data:
            project, created = Project.objects.get_or_create(kicc_project_id=project_data['kicc_project_id'], defaults=project_data)
            if created:
                self.stdout.write(f'Created project: {project.title}')
            else:
                self.stdout.write(f'Project {project.title} already exists')

    def create_news_events(self):
        news_events_data = [
            # EDUCATION NEWS
            {'title': 'New Volunteer Program Launch', 'body': 'We are excited to announce the launch of our newest volunteer program focused on digital literacy for seniors.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=5), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/program,launch'},
            {'title': 'Education Access Initiative Expands', 'body': 'We expand our education initiatives to 10 new villages, reaching 500 more children.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=8), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/education,initiative'},
            {'title': 'Tech Skills Program Launches', 'body': 'Launch of coding and technology skills program for 300 underprivileged youth.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=6), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/tech,skills'},
            {'title': 'School Building Project Inaugurated', 'body': 'New school building inaugurated, providing education to 500 rural children.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=11), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/school,building'},
            {'title': 'Community Library Opens', 'body': 'First community library opens with 500 books, serving 300 families.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=9), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/library,community'},
            # HEALTHCARE NEWS
            {'title': 'Healthcare Camp in Rural Areas', 'body': 'Our healthcare outreach team conducted free medical camps in 5 villages, providing health check-ups to over 1000 people.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=20), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/healthcare,camp'},
            {'title': 'Child Nutrition Program Impact Report', 'body': 'Our nutrition program has improved health outcomes for 800 malnourished children.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=22), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/child,nutrition'},
            {'title': 'Health Center Opens in Remote Area', 'body': 'Community health center now serving 3000 residents in remote area.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=2), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/health,center'},
            # ENVIRONMENT NEWS
            {'title': 'Environmental Conservation Success', 'body': 'Our environmental conservation project has successfully planted over 50,000 trees in the past year.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=15), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/environment,conservation'},
            {'title': 'Water & Sanitation Project Completed', 'body': 'Successfully completed water and sanitation infrastructure in 8 villages, benefiting 5000 residents.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=18), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/water,sanitation'},
            {'title': 'Agricultural Training Completes First Batch', 'body': 'First batch of 200 farmers trained in sustainable agriculture techniques.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=30), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/agriculture,training'},
            {'title': 'Renewable Energy Training Completes', 'body': 'Renewable energy training program completes, training 100 professionals.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=24), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/renewable,energy'},
            # WOMEN EMPOWERMENT NEWS
            {'title': 'Women Empowerment Milestone', 'body': 'We celebrate empowering 500 women through our vocational training programs.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=25), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/women,empowerment'},
            {'title': 'Gender Equality Campaign Reaches 5000', 'body': 'Gender equality awareness campaign reaches milestone of 5000 participants.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=27), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/gender,equality'},
            {'title': 'Microfinance Program Disburses Loans', 'body': 'Microfinance program disburses loans to 300 women entrepreneurs.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=13), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/microfinance,loans'},
            # DISASTER RELIEF NEWS
            {'title': 'Disaster Relief Response Update', 'body': 'Following the recent floods, our rapid response team has provided relief to over 2000 families.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=3), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/disaster,relief'},
            {'title': 'Disaster Preparedness Training Conducted', 'body': 'Disaster preparedness training completed in 10 communities.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=26), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/disaster,preparedness'},
            # MENTAL HEALTH NEWS
            {'title': 'Mental Health Awareness Workshop', 'body': 'Our mental health awareness campaign reaches 2000 people through workshops and community sessions.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=7), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/mental,health'},
            # SKILLS & DEVELOPMENT
            {'title': 'Artisan Skills Program Impact', 'body': '150 artisans trained in modern marketing and online skills.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=23), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/artisan,skills'},
            # YOUTH & SPORTS
            {'title': 'Sports Facility Construction Completed', 'body': 'Community sports facility now operational, serving 1000 youth members.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=16), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/sports,facility'},
            # ELDER CARE
            {'title': 'Elderly Care Initiative Begins', 'body': 'New elderly care support program now active in 5 care homes.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=14), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/elderly,care'},
            # ANIMAL WELFARE
            {'title': 'Animal Welfare Center Opens', 'body': 'New animal welfare center provides veterinary services to 200 animals.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=17), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/animal,welfare'},
            # REFUGEE SUPPORT
            {'title': 'Refugee Integration Success Stories', 'body': 'Refugee integration program helps 100 families settle successfully.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=19), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/refugee,integration'},
            # CHILD WELFARE
            {'title': 'Child Protection Program Expands', 'body': 'Child protection program now operating in 12 districts.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=21), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,protection'},
            # GENERAL VOLUNTEER
            {'title': 'Annual Volunteer Summit 2024', 'body': 'Join us for our annual volunteer summit where volunteers from around the world come together to share experiences.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=10), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/volunteer,summit'},
            {'title': 'Volunteer Recognition Awards 2024', 'body': 'Celebrating our outstanding volunteers who have made exceptional contributions to our mission.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=12), 'is_published': True, 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/volunteer,awards'},
            {'title': 'Language Exchange Program Begins', 'body': 'Language and cultural exchange program connects 200 volunteers internationally.', 'content_type': 'EVENT', 'publish_date': timezone.now() - timedelta(days=4), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/language,exchange'},
            {'title': 'Microenterprise Support Program Launches', 'body': 'Support program helps 50 community members start microenterprises.', 'content_type': 'NEWS', 'publish_date': timezone.now() - timedelta(days=29), 'is_published': True, 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/microenterprise,support'},
        ]

        for news_data in news_events_data:
            news, created = NewsEvent.objects.get_or_create(title=news_data['title'], defaults=news_data)
            if created:
                self.stdout.write(f'Created news/event: {news.title}')
            else:
                self.stdout.write(f'News/Event {news.title} already exists')

    def create_success_stories(self):
        projects = list(Project.objects.all())
        if not projects:
            self.stdout.write('No projects found, skipping success stories')
            return

        success_stories_data = [
            # EDUCATION STORIES
            {'title': 'Transforming Lives Through Education', 'body': 'Asha, a bright young student from a rural village, struggled with computer science and English communication. Through our education program, paired with dedicated volunteer Sankit, she learned to create presentations and speak confidently.', 'related_project': random.choice([p for p in projects if 'Education' in p.title]), 'beneficiaries': 150, 'total_hours_contributed': 500, 'is_published': True, 'published_at': timezone.now() - timedelta(days=20), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/education,program/?random=1', 'image_urls': ['https://loremflickr.com/320/240/education,program/?random=1', 'https://loremflickr.com/320/240/volunteer,skills/?random=2', 'https://loremflickr.com/320/240/children,learning/?random=3'], 'video_urls': ['https://www.youtube.com/watch?v=beCPqm1UlHY', 'https://www.youtube.com/watch?v=pxP9-Jx9bNc']},
            {'title': 'Tech Skills Employment', 'body': 'Our tech skills program has trained 300 youth in coding and programming, resulting in 80% employment rate in tech companies within 6 months of training completion.', 'related_project': random.choice([p for p in projects if 'Education' in p.title or 'Tech' in p.title]), 'beneficiaries': 300, 'total_hours_contributed': 700, 'is_published': True, 'published_at': timezone.now() - timedelta(days=43), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/tech,skills/?random=1', 'image_urls': ['https://loremflickr.com/320/240/tech,skills/?random=1', 'https://loremflickr.com/320/240/programming,employment/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=CI3P0ndNXuE']},
            {'title': 'Community Library Impact', 'body': 'Our community library now serves 300 families with over 5000 books. Student reading levels have improved by 30% in the first year of operation.', 'related_project': random.choice([p for p in projects if 'Education' in p.title or 'Library' in p.title]), 'beneficiaries': 300, 'total_hours_contributed': 400, 'is_published': True, 'published_at': timezone.now() - timedelta(days=26), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/library,books/?random=1', 'image_urls': ['https://loremflickr.com/320/240/library,books/?random=1'], 'video_urls': []},
            {'title': 'School Construction Impact', 'body': 'Our school building project has constructed 2 new schools in rural areas, providing quality education to 500 children who previously had no access to schooling.', 'related_project': random.choice([p for p in projects if 'School' in p.title]), 'beneficiaries': 500, 'total_hours_contributed': 900, 'is_published': True, 'published_at': timezone.now() - timedelta(days=49), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/school,construction/?random=1', 'image_urls': ['https://loremflickr.com/320/240/school,construction/?random=1', 'https://loremflickr.com/320/240/education,rural/?random=2'], 'video_urls': []},
            # HEALTHCARE STORIES
            {'title': 'Building Healthy Communities', 'body': 'Our healthcare outreach initiative has made significant impact in remote villages. Volunteers conducted 20 medical camps, provided health education to over 3000 people, and established basic health awareness programs in 15 villages.', 'related_project': random.choice([p for p in projects if 'Healthcare' in p.title or 'Health' in p.title]), 'beneficiaries': 3000, 'total_hours_contributed': 800, 'is_published': True, 'published_at': timezone.now() - timedelta(days=35), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/healthcare,outreach/?random=1', 'image_urls': ['https://loremflickr.com/320/240/healthcare,outreach/?random=1', 'https://loremflickr.com/320/240/medical,camp/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=CI3P0ndNXuE']},
            {'title': 'Child Nutrition Success', 'body': 'Our child nutrition program has improved the health of 800 malnourished children. With regular nutritious meals, children showed improved academic performance and better overall development.', 'related_project': random.choice([p for p in projects if 'Nutrition' in p.title or 'Health' in p.title]), 'beneficiaries': 800, 'total_hours_contributed': 600, 'is_published': True, 'published_at': timezone.now() - timedelta(days=40), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,nutrition/?random=1', 'image_urls': ['https://loremflickr.com/320/240/child,nutrition/?random=1', 'https://loremflickr.com/320/240/health,children/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=E16iOaAP4SQ']},
            {'title': 'Health Centers Operational', 'body': 'Our community health centers are now operational in 3 remote areas, providing primary healthcare to 5000 residents who previously had no access.', 'related_project': random.choice([p for p in projects if 'Health' in p.title]), 'beneficiaries': 5000, 'total_hours_contributed': 1200, 'is_published': True, 'published_at': timezone.now() - timedelta(days=39), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/health,center/?random=1', 'image_urls': ['https://loremflickr.com/320/240/health,center/?random=1', 'https://loremflickr.com/320/240/healthcare,remote/?random=2', 'https://loremflickr.com/320/240/community,health/?random=3'], 'video_urls': ['https://www.youtube.com/watch?v=QFYs89VWRFA', 'https://www.youtube.com/watch?v=E16iOaAP4SQ']},
            {'title': 'HIV/AIDS Awareness Growth', 'body': 'Our HIV/AIDS awareness program has reached 3000 people with education and support services, resulting in increased testing rates and reduced stigma in communities.', 'related_project': random.choice([p for p in projects if 'AIDS' in p.title or 'Health' in p.title]), 'beneficiaries': 3000, 'total_hours_contributed': 450, 'is_published': True, 'published_at': timezone.now() - timedelta(days=52), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/hiv,aids/?random=1', 'image_urls': ['https://loremflickr.com/320/240/hiv,aids/?random=1', 'https://loremflickr.com/320/240/health,awareness/?random=2'], 'video_urls': []},
            # ENVIRONMENT STORIES
            {'title': 'Green Revolution: Trees for Tomorrow', 'body': 'Through our environmental conservation project, volunteers planted over 50,000 trees across 20 villages. This initiative not only contributed to environmental restoration but also created 200 temporary jobs for local community members.', 'related_project': random.choice([p for p in projects if 'Environment' in p.title or 'Conservation' in p.title]), 'beneficiaries': 2000, 'total_hours_contributed': 1200, 'is_published': True, 'published_at': timezone.now() - timedelta(days=45), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/environment,conservation/?random=1', 'image_urls': ['https://loremflickr.com/320/240/environment,conservation/?random=1', 'https://loremflickr.com/320/240/trees,planting/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=LEe0p_hSiNA', 'https://www.youtube.com/watch?v=evyNG3XmjfE']},
            {'title': 'Water Access Changes Lives', 'body': 'Our water and sanitation project brought clean water access to 5000 people in 8 villages. The impact has been transformative - disease rates dropped by 60% and children now have more time for school instead of water collection.', 'related_project': random.choice([p for p in projects if 'Water' in p.title or 'Sanitation' in p.title]), 'beneficiaries': 5000, 'total_hours_contributed': 1000, 'is_published': True, 'published_at': timezone.now() - timedelta(days=55), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/water,access/?random=1', 'image_urls': ['https://loremflickr.com/320/240/water,access/?random=1', 'https://loremflickr.com/320/240/sanitation,rural/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=QFYs89VWRFA']},
            {'title': 'Environmental Cleanup Success', 'body': 'Our environmental cleanup drive collected 500 tons of waste and restored local water bodies. Participants developed greater environmental consciousness and community engagement.', 'related_project': random.choice([p for p in projects if 'Environment' in p.title or 'Cleanup' in p.title]), 'beneficiaries': 1000, 'total_hours_contributed': 700, 'is_published': True, 'published_at': timezone.now() - timedelta(days=25), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/environment,cleanup/?random=1', 'image_urls': ['https://loremflickr.com/320/240/environment,cleanup/?random=1', 'https://loremflickr.com/320/240/waste,reduction/?random=2'], 'video_urls': []},
            {'title': 'Farmers Increase Yields', 'body': 'Through our agricultural development project, 200 farmers have adopted sustainable farming practices, increasing yields by an average of 40% and improving their income.', 'related_project': random.choice([p for p in projects if 'Agricultural' in p.title]), 'beneficiaries': 200, 'total_hours_contributed': 500, 'is_published': True, 'published_at': timezone.now() - timedelta(days=38), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/agriculture,farming/?random=1', 'image_urls': ['https://loremflickr.com/320/240/agriculture,farming/?random=1', 'https://loremflickr.com/320/240/sustainable,agriculture/?random=2'], 'video_urls': []},
            {'title': 'Renewable Energy Adoption', 'body': 'Our renewable energy education program has helped 100 households adopt solar energy, reducing their electricity costs by 50% and carbon footprint significantly.', 'related_project': random.choice([p for p in projects if 'Renewable' in p.title]), 'beneficiaries': 100, 'total_hours_contributed': 350, 'is_published': True, 'published_at': timezone.now() - timedelta(days=51), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/renewable,energy/?random=1', 'image_urls': ['https://loremflickr.com/320/240/renewable,energy/?random=1', 'https://loremflickr.com/320/240/solar,power/?random=2'], 'video_urls': []},
            # WOMEN EMPOWERMENT STORIES
            {'title': 'Women Leaders Rising', 'body': 'Our women empowerment program has transformed 500 women into skilled professionals and entrepreneurs. Participants learned vocational skills, business management, and leadership. Today, 80% of graduates have started their own small businesses.', 'related_project': random.choice([p for p in projects if 'Women' in p.title or 'Empowerment' in p.title]), 'beneficiaries': 500, 'total_hours_contributed': 650, 'is_published': True, 'published_at': timezone.now() - timedelta(days=50), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/women,empowerment/?random=1', 'image_urls': ['https://loremflickr.com/320/240/women,empowerment/?random=1', 'https://loremflickr.com/320/240/entrepreneur,women/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=uidICeB1ys8', 'https://www.youtube.com/watch?v=jUWFotCfiVI']},
            {'title': 'Gender Equality Progress', 'body': 'Our gender equality advocacy has reached 5000 people and successfully changed community attitudes in 15 villages, leading to increased women participation in decision-making.', 'related_project': random.choice([p for p in projects if 'Gender' in p.title]), 'beneficiaries': 5000, 'total_hours_contributed': 400, 'is_published': True, 'published_at': timezone.now() - timedelta(days=34), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/gender,equality/?random=1', 'image_urls': ['https://loremflickr.com/320/240/gender,equality/?random=1', 'https://loremflickr.com/320/240/women,rights/?random=2'], 'video_urls': []},
            {'title': 'Microfinance Empowerment', 'body': 'Our microfinance program has disbursed loans to 300 women entrepreneurs, resulting in 250 of them starting successful businesses and becoming self-reliant.', 'related_project': random.choice([p for p in projects if 'Microfinance' in p.title]), 'beneficiaries': 300, 'total_hours_contributed': 450, 'is_published': True, 'published_at': timezone.now() - timedelta(days=29), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/microfinance,women/?random=1', 'image_urls': ['https://loremflickr.com/320/240/microfinance,women/?random=1', 'https://loremflickr.com/320/240/entrepreneur,loans/?random=2'], 'video_urls': []},
            # DISASTER RELIEF STORIES
            {'title': 'Recovery and Resilience', 'body': 'After devastating floods, our disaster relief team worked tirelessly to help 2000 families rebuild their lives. Volunteers provided emergency shelter, food, water, and counseling. The rehabilitation phase included helping families reconstruct homes.', 'related_project': random.choice([p for p in projects if 'Disaster' in p.title]), 'beneficiaries': 2000, 'total_hours_contributed': 1500, 'is_published': True, 'published_at': timezone.now() - timedelta(days=60), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/disaster,relief/?random=1', 'image_urls': ['https://loremflickr.com/320/240/disaster,relief/?random=1', 'https://loremflickr.com/320/240/flood,recovery/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=9f5ynZdDuTM']},
            {'title': 'Disaster Preparedness Network', 'body': 'Our disaster preparedness training has equipped 10 communities with skills to respond effectively to emergencies, reducing disaster-related casualties by 40%.', 'related_project': random.choice([p for p in projects if 'Disaster' in p.title]), 'beneficiaries': 1000, 'total_hours_contributed': 500, 'is_published': True, 'published_at': timezone.now() - timedelta(days=47), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/disaster,preparedness/?random=1', 'image_urls': ['https://loremflickr.com/320/240/disaster,preparedness/?random=1'], 'video_urls': []},
            # MENTAL HEALTH STORIES
            {'title': 'Mental Health Awareness Impact', 'body': 'Our mental health awareness campaign has reached 2000 people and helped 150 individuals seek professional treatment for their mental health issues.', 'related_project': random.choice([p for p in projects if 'Mental' in p.title]), 'beneficiaries': 2000, 'total_hours_contributed': 350, 'is_published': True, 'published_at': timezone.now() - timedelta(days=33), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/mental,health/?random=1', 'image_urls': ['https://loremflickr.com/320/240/mental,health/?random=1', 'https://loremflickr.com/320/240/therapy,support/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=0k88vwkSFRE']},
            # SKILLS TRAINING STORIES
            {'title': 'Artisans Reach Global Market', 'body': 'Our artisan skills training program helped 150 traditional artisans learn digital marketing, resulting in 40 of them starting online businesses and reaching international customers.', 'related_project': random.choice([p for p in projects if 'Artisan' in p.title]), 'beneficiaries': 150, 'total_hours_contributed': 600, 'is_published': True, 'published_at': timezone.now() - timedelta(days=48), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/artisan,market/?random=1', 'image_urls': ['https://loremflickr.com/320/240/artisan,market/?random=1'], 'video_urls': []},
            # YOUTH DEVELOPMENT STORIES
            {'title': 'Youth Sports Excellence', 'body': 'Through our sports development initiative, 500 youth have gained confidence, fitness, and leadership skills. Three of our participants have won state-level sports competitions.', 'related_project': random.choice([p for p in projects if 'Sports' in p.title]), 'beneficiaries': 500, 'total_hours_contributed': 550, 'is_published': True, 'published_at': timezone.now() - timedelta(days=28), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/youth,sports/?random=1', 'image_urls': ['https://loremflickr.com/320/240/youth,sports/?random=1', 'https://loremflickr.com/320/240/sports,training/?random=2'], 'video_urls': []},
            {'title': 'Sports Facility Community Hub', 'body': 'Our sports facility has become a community hub serving 1000 youth members monthly. The facility has reduced youth engagement in negative activities by 50%.', 'related_project': random.choice([p for p in projects if 'Sports' in p.title]), 'beneficiaries': 1000, 'total_hours_contributed': 600, 'is_published': True, 'published_at': timezone.now() - timedelta(days=32), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/sports,facility/?random=1', 'image_urls': ['https://loremflickr.com/320/240/sports,facility/?random=1', 'https://loremflickr.com/320/240/community,recreation/?random=2'], 'video_urls': []},
            # ELDERLY CARE STORIES
            {'title': 'Elderly Companionship Program', 'body': 'Our elderly care support program has provided companionship and support to 400 senior citizens, improving their mental health and reducing loneliness.', 'related_project': random.choice([p for p in projects if 'Elderly' in p.title]), 'beneficiaries': 400, 'total_hours_contributed': 500, 'is_published': True, 'published_at': timezone.now() - timedelta(days=36), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/elderly,care/?random=1', 'image_urls': ['https://loremflickr.com/320/240/elderly,care/?random=1'], 'video_urls': []},
            {'title': 'Connecting Seniors with Technology', 'body': 'Our digital literacy program helped 300 senior citizens learn basic computer and internet skills. Volunteers patiently taught them to use email, video calls, and online safety. The program has enabled seniors to stay connected with family members.', 'related_project': random.choice(projects), 'beneficiaries': 300, 'total_hours_contributed': 400, 'is_published': True, 'published_at': timezone.now() - timedelta(days=30), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/digital,literacy/?random=1', 'image_urls': ['https://loremflickr.com/320/240/digital,literacy/?random=1', 'https://loremflickr.com/320/240/seniors,tech/?random=2'], 'video_urls': []},
            # ANIMAL WELFARE STORIES
            {'title': 'Animal Welfare Saves Lives', 'body': 'Our animal welfare program has provided free veterinary care to 1000 animals and educated 500 people on animal rights and care.', 'related_project': random.choice([p for p in projects if 'Animal' in p.title]), 'beneficiaries': 500, 'total_hours_contributed': 400, 'is_published': True, 'published_at': timezone.now() - timedelta(days=31), 'is_featured': False, 'cover_image_url': 'https://loremflickr.com/320/240/animal,welfare/?random=1', 'image_urls': ['https://loremflickr.com/320/240/animal,welfare/?random=1'], 'video_urls': []},
            # REFUGEE SUPPORT STORIES
            {'title': 'Refugee Integration Success', 'body': 'Our refugee support program has helped 150 families integrate successfully into their new communities through language training, employment support, and cultural orientation.', 'related_project': random.choice([p for p in projects if 'Refugee' in p.title]), 'beneficiaries': 150, 'total_hours_contributed': 650, 'is_published': True, 'published_at': timezone.now() - timedelta(days=46), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/refugee,integration/?random=1', 'image_urls': ['https://loremflickr.com/320/240/refugee,integration/?random=1', 'https://loremflickr.com/320/240/cultural,exchange/?random=2'], 'video_urls': []},
            # CHILD WELFARE STORIES
            {'title': 'Street Children Transformed', 'body': 'Our street children rehabilitation program has provided shelter and education to 200 children. Many have now returned to formal schooling and are on a path to brighter futures.', 'related_project': random.choice([p for p in projects if 'Child' in p.title]), 'beneficiaries': 200, 'total_hours_contributed': 800, 'is_published': True, 'published_at': timezone.now() - timedelta(days=42), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,welfare/?random=1', 'image_urls': ['https://loremflickr.com/320/240/child,welfare/?random=1'], 'video_urls': []},
            {'title': 'Child Protection Network', 'body': 'Our child protection program has established a network across 12 districts, protecting 500 children from exploitation and providing rehabilitation services.', 'related_project': random.choice([p for p in projects if 'Child' in p.title]), 'beneficiaries': 500, 'total_hours_contributed': 750, 'is_published': True, 'published_at': timezone.now() - timedelta(days=37), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/child,protection/?random=1', 'image_urls': ['https://loremflickr.com/320/240/child,protection/?random=1', 'https://loremflickr.com/320/240/exploitation,prevention/?random=2'], 'video_urls': []},
            # ECONOMIC DEVELOPMENT STORIES
            {'title': 'Microenterprise Success Stories', 'body': 'Our microenterprise support program has helped 50 community members start businesses, creating 150 jobs and generating collective revenue of $100,000 in the first year.', 'related_project': random.choice([p for p in projects if 'Microenterprise' in p.title]), 'beneficiaries': 50, 'total_hours_contributed': 350, 'is_published': True, 'published_at': timezone.now() - timedelta(days=41), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/microenterprise,business/?random=1', 'image_urls': ['https://loremflickr.com/320/240/microenterprise,business/?random=1', 'https://loremflickr.com/320/240/economic,development/?random=2'], 'video_urls': ['https://www.youtube.com/watch?v=uidICeB1ys8']},
            # LANGUAGE & CULTURE STORIES
            {'title': 'Language & Culture Exchange', 'body': 'Our language and cultural exchange program has connected 200 volunteers across 10 countries, fostering global understanding and friendship.', 'related_project': random.choice([p for p in projects if 'Language' in p.title]), 'beneficiaries': 200, 'total_hours_contributed': 300, 'is_published': True, 'published_at': timezone.now() - timedelta(days=44), 'is_featured': True, 'cover_image_url': 'https://loremflickr.com/320/240/language,culture/?random=1', 'image_urls': ['https://loremflickr.com/320/240/language,culture/?random=1', 'https://loremflickr.com/320/240/cultural,exchange/?random=2'], 'video_urls': []},
        ]

        for story_data in success_stories_data:
            story, created = SuccessStory.objects.get_or_create(title=story_data['title'], defaults=story_data)
            if created:
                self.stdout.write(f'Created success story: {story.title}')
            else:
                self.stdout.write(f'Success story {story.title} already exists')

    def create_faqs(self):
        faqs_data = [
            {'question': 'How do I apply for a volunteer project?', 'answer': 'To apply for a volunteer project, create an account on our platform and browse available opportunities. Click on any project that interests you and submit your application.', 'order': 1},
            {'question': 'What are the eligibility requirements for volunteering?', 'answer': 'Eligibility requirements vary by project. Most projects require you to be at least 18 years old and committed to the project duration.', 'order': 2},
            {'question': 'Do I need prior experience to volunteer?', 'answer': 'While some projects prefer prior experience, many welcome enthusiastic individuals with no prior experience. We provide training and support to all volunteers.', 'order': 3},
            {'question': 'What is the typical duration of a volunteer project?', 'answer': 'Project durations vary from 6 months to 2 years. Each project description clearly specifies the commitment period. You can choose projects that align with your available time.', 'order': 4},
            {'question': 'Are volunteers provided with accommodation and meals?', 'answer': 'Accommodation and meal provisions depend on the specific project. Most international projects provide basic accommodation and meals.', 'order': 5},
            {'question': 'Is there any financial support for volunteers?', 'answer': 'While we don\'t provide salary, most projects cover accommodation, meals, and local transportation. Some projects may offer stipends depending on funding.', 'order': 6},
            {'question': 'How can I stay safe while volunteering?', 'answer': 'Safety is our top priority. We conduct thorough background checks, provide pre-departure briefings, arrange travel insurance, and maintain 24/7 contact support.', 'order': 7},
            {'question': 'Will I receive a certificate after completing the project?', 'answer': 'Yes, all volunteers who successfully complete their projects receive a completion certificate. We also provide recommendation letters.', 'order': 8},
            {'question': 'Can I extend my volunteer period?', 'answer': 'Extensions depend on project availability and organizational capacity. Contact your project coordinator to discuss extension possibilities.', 'order': 9},
            {'question': 'What should I do if I have concerns during my volunteering?', 'answer': 'We encourage open communication. Contact your project coordinator, our support team, or use our anonymous feedback form.', 'order': 10},
            {'question': 'What documents do I need to bring?', 'answer': 'Required documents typically include passport, visa (if applicable), travel insurance documents, vaccination certificates, and project-specific requirements.', 'order': 11},
            {'question': 'How are volunteers selected?', 'answer': 'Volunteers are selected based on their application, motivation, skills, and fit for the project. We review all applications carefully.', 'order': 12},
            {'question': 'Can I volunteer with my family or friends?', 'answer': 'Yes, you can volunteer with family members or friends. Group applications are welcome and encouraged for many of our projects.', 'order': 13},
            {'question': 'What is the application process timeline?', 'answer': 'Typically, applications are reviewed within 2-3 weeks. Selected candidates are notified and given time to prepare before project start date.', 'order': 14},
            {'question': 'Are there age restrictions for volunteering?', 'answer': 'Most projects require volunteers to be 18 years or older. Some projects may welcome younger volunteers with parental consent and appropriate supervision.', 'order': 15},
            {'question': 'What happens if I cannot complete my volunteer commitment?', 'answer': 'We understand that circumstances change. Please contact us immediately to discuss your situation. We\'ll work with you to find solutions.', 'order': 16},
            {'question': 'How will I communicate with my family while volunteering?', 'answer': 'Most project locations have internet access. We ensure volunteers can maintain contact with their families through email, messaging apps, or calls.', 'order': 17},
            {'question': 'What kind of training will I receive?', 'answer': 'All volunteers receive orientation and project-specific training before beginning work. Ongoing support and training are provided throughout your volunteering period.', 'order': 18},
            {'question': 'Are there volunteer opportunities for students?', 'answer': 'Yes, we have many opportunities for students. We can often work with your academic calendar to accommodate your schedule.', 'order': 19},
            {'question': 'What is the cost of volunteering?', 'answer': 'Program costs vary by project and location. Some projects are fully sponsored while others require a participation fee. Details are provided in each project description.', 'order': 20},
            {'question': 'How do I prepare physically for volunteering?', 'answer': 'Physical preparation depends on your project. We provide guidance on fitness requirements and health recommendations during the application process.', 'order': 21},
            {'question': 'What languages are required?', 'answer': 'Language requirements vary by project. Most projects work in English, but some may require or prefer knowledge of local languages.', 'order': 22},
            {'question': 'Will I get a job after volunteering?', 'answer': 'While we cannot guarantee employment, volunteer experience strengthens your resume. Many organizations hire volunteers based on their performance.', 'order': 23},
            {'question': 'How do I stay connected with other volunteers?', 'answer': 'We maintain alumni networks, Facebook groups, and organize reunions where volunteers can stay connected and share experiences.', 'order': 24},
            {'question': 'What is your cancellation policy?', 'answer': 'Cancellation policies vary by program. Details are provided at the time of booking. We recommend travel insurance to cover unexpected circumstances.', 'order': 25},
            {'question': 'Can volunteers work on multiple projects?', 'answer': 'Yes, after completing one project, you can apply for others. Many of our volunteers engage in multiple projects over time.', 'order': 26},
            {'question': 'How will I be matched to the right project?', 'answer': 'Our matching process considers your skills, interests, experience, and project requirements to ensure the best fit for both you and the community.', 'order': 27},
            {'question': 'What support is available for volunteers with disabilities?', 'answer': 'We are committed to inclusive volunteering. Please contact us to discuss accommodations needed for your specific situation.', 'order': 28},
            {'question': 'How do I know if a project is legitimate?', 'answer': 'All projects are vetted by our team for authenticity and impact. Scams typically ask for upfront fees or provide vague project details.', 'order': 29},
            {'question': 'What happens after I complete my volunteer service?', 'answer': 'After completion, you\'ll receive a certificate, recommendation letter, and alumni status. You\'ll also be invited to share feedback and success stories.', 'order': 30},
        ]

        for faq_data in faqs_data:
            faq, created = FAQ.objects.get_or_create(question=faq_data['question'], defaults=faq_data)
            if created:
                self.stdout.write(f'Created FAQ: {faq.question}')
            else:
                self.stdout.write(f'FAQ {faq.question} already exists')