from django.core.management.base import BaseCommand
from django.utils import timezone
from apps.content.models import Project
from datetime import timedelta
import random

class Command(BaseCommand):
    help = 'Seeds the database with Project data (EN & ZH-TW) using LoremFlickr and Kingslish Video'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding Projects...')

        # Common video from the Kingslish channel for seeding
        # Note: In a real scenario, you would pick specific video IDs from the channel.
        # Here we point to the channel or a representative video format.
        KINGSLISH_CHANNEL_VIDEO = "https://www.youtube.com/watch?v=example_video_id_from_kingslish" 

        projects_data = [
            {
                # English
                "title_en": "English Teaching in Rural Schools",
                "teaser_en": "Help children in remote villages improve their English skills and open doors to new opportunities.",
                "background_objectives_en": "Many rural schools lack resources. Our objective is to provide native-level conversation practice.",
                "tasks_eligibility_en": "Tasks: conduct classes, organize games. Eligibility: Fluent English, patience.",
                "country_en": "Vietnam",
                "theme_en": "Education",
                
                # Traditional Chinese (ZH-TW)
                "title_zh_tw": "偏遠地區學校英語教學",
                "teaser_zh_tw": "幫助偏遠鄉村的兒童提升英語能力，為他們開啟通往新機遇的大門。",
                "background_objectives_zh_tw": "許多鄉村學校缺乏資源。我們的目標是提供母語級別的會話練習。",
                "tasks_eligibility_zh_tw": "任務：授課、組織遊戲。資格：英語流利、有耐心。",
                "country_zh_tw": "越南",
                "theme_zh_tw": "教育",

                # Metadata & Media
                "kicc_project_id": "EDU-VN-001",
                "duration": 40,
                "difficulty": "Medium",
                "total_headcount": 20,
                
                # Images via Lorem Flickr with specific keywords
                "cover_image_url": "https://loremflickr.com/800/600/classroom,vietnam,students",
                "image_urls": [
                    "https://loremflickr.com/800/600/teacher,blackboard,1",
                    "https://loremflickr.com/800/600/teacher,blackboard,2",
                    "https://loremflickr.com/800/600/school,children,1",
                    "https://loremflickr.com/800/600/school,children,2",
                    "https://loremflickr.com/800/600/book,learning,1",
                    "https://loremflickr.com/800/600/book,learning,2",
                    "https://loremflickr.com/800/600/classroom,teaching,1",
                    "https://loremflickr.com/800/600/classroom,teaching,2",
                    "https://loremflickr.com/800/600/volunteer,teacher,1",
                    "https://loremflickr.com/800/600/volunteer,teacher,2",
                    "https://loremflickr.com/800/600/teaching,materials,1",
                    "https://loremflickr.com/800/600/teaching,materials,2",
                    "https://loremflickr.com/800/600/game,learning,1",
                    "https://loremflickr.com/800/600/game,learning,2",
                    "https://loremflickr.com/800/600/group,learning,1",
                    "https://loremflickr.com/800/600/group,learning,2",
                    "https://loremflickr.com/800/600/chart,education,1",
                    "https://loremflickr.com/800/600/chart,education,2",
                    "https://loremflickr.com/800/600/whiteboard,1",
                    "https://loremflickr.com/800/600/whiteboard,2",
                    "https://loremflickr.com/800/600/exam,help,1",
                    "https://loremflickr.com/800/600/exam,help,2",
                    "https://loremflickr.com/800/600/reading,1",
                    "https://loremflickr.com/800/600/reading,2",
                ],
                
                # Videos from Kingslish App Channel
                "video_urls": [
                    "https://www.youtube.com/watch?v=2026_AHS_Taiwan_Trip", # Placeholder for actual channel video
                    "https://www.youtube.com/@kingslishapp" # Fallback to channel URL
                ],

                "application_deadline": timezone.now() + timedelta(days=30),
                "start_date": timezone.now().date() + timedelta(days=45),
                "end_date": timezone.now().date() + timedelta(days=60),
                "is_featured": True,
            },
            {
                # English
                "title_en": "Community Health & Outreach",
                "teaser_en": "Deliver essential health education and basic screenings to remote communities.",
                "background_objectives_en": "Many remote areas lack basic healthcare. We aim to provide health education and screening campaigns.",
                "tasks_eligibility_en": "Tasks: provide basic screenings, teach hygiene. Eligibility: health background preferred, patient-centered.",
                "country_en": "Cambodia",
                "theme_en": "Health",

                # Traditional Chinese (ZH-TW)
                "title_zh_tw": "社區健康與外展",
                "teaser_zh_tw": "為偏遠社區提供基本健康教育與檢查。",
                "background_objectives_zh_tw": "許多偏遠地區缺乏基本醫療。我們的目標是提供健康教育與篩檢活動。",
                "tasks_eligibility_zh_tw": "任務：提供基礎篩檢、教授衛生教育。資格：具醫療背景優先、耐心。",
                "country_zh_tw": "柬埔寨",
                "theme_zh_tw": "健康",

                # Metadata & Media
                "kicc_project_id": "HLT-KH-003",
                "duration": 30,
                "difficulty": "Medium",
                "total_headcount": 30,

                # Images via Lorem Flickr (24 images)
                "cover_image_url": "https://loremflickr.com/800/600/clinic,health,community",
                "image_urls": [
                    "https://loremflickr.com/800/600/clinic,health,1",
                    "https://loremflickr.com/800/600/clinic,health,2",
                    "https://loremflickr.com/800/600/hygiene,education,1",
                    "https://loremflickr.com/800/600/hygiene,education,2",
                    "https://loremflickr.com/800/600/doctor,nurse,1",
                    "https://loremflickr.com/800/600/doctor,nurse,2",
                    "https://loremflickr.com/800/600/village,clinic,1",
                    "https://loremflickr.com/800/600/village,clinic,2",
                    "https://loremflickr.com/800/600/child,checkup,1",
                    "https://loremflickr.com/800/600/child,checkup,2",
                    "https://loremflickr.com/800/600/medical,kit,1",
                    "https://loremflickr.com/800/600/medical,kit,2",
                    "https://loremflickr.com/800/600/fieldclinic,1",
                    "https://loremflickr.com/800/600/fieldclinic,2",
                    "https://loremflickr.com/800/600/community,workshop,1",
                    "https://loremflickr.com/800/600/community,workshop,2",
                    "https://loremflickr.com/800/600/vaccine,education,1",
                    "https://loremflickr.com/800/600/vaccine,education,2",
                    "https://loremflickr.com/800/600/volunteer,health,1",
                    "https://loremflickr.com/800/600/volunteer,health,2",
                    "https://loremflickr.com/800/600/smiling,children,1",
                    "https://loremflickr.com/800/600/smiling,children,2",
                    "https://loremflickr.com/800/600/hands,washing,1",
                    "https://loremflickr.com/800/600/hands,washing,2",
                ],

                # Videos
                "video_urls": [
                    "https://www.youtube.com/watch?v=kingslish_example_1",
                ],

                "application_deadline": timezone.now() + timedelta(days=18),
                "start_date": timezone.now().date() + timedelta(days=25),
                "end_date": timezone.now().date() + timedelta(days=33),
                "is_featured": False,
            },
            {
                "title_en": "Renewable Energy: Solar Village Electrification",
                "teaser_en": "Help build small solar grids to provide power to remote agricultural villages.",
                "background_objectives_en": "Access to electricity helps extend study hours and improve livelihoods. We will install microgrid solutions and teach maintenance.",
                "tasks_eligibility_en": "Tasks: Solar panel installation, system maintenance. Eligibility: electrical/engineering & good communication.",
                "country_en": "Laos",
                "theme_en": "Energy",

                "title_zh_tw": "再生能源：太陽能村莊電氣化",
                "teaser_zh_tw": "協助打造小型太陽能電網，為偏遠農村提供電力。",
                "background_objectives_zh_tw": "電力可延長讀書時間並改善生計。我們將安裝微電網並教導維護。",
                "tasks_eligibility_zh_tw": "任務：太陽能板安裝、系統維護。資格：電機／工程背景與良好溝通能力。",
                "country_zh_tw": "寮國",
                "theme_zh_tw": "能源",

                "kicc_project_id": "ENE-LA-004",
                "duration": 45,
                "difficulty": "Hard",
                "total_headcount": 12,
                "cover_image_url": "https://loremflickr.com/800/600/solar,panels,village",
                "image_urls": [
                    "https://loremflickr.com/800/600/solar,panels,1",
                    "https://loremflickr.com/800/600/solar,panels,2",
                    "https://loremflickr.com/800/600/solar,installation,1",
                    "https://loremflickr.com/800/600/solar,installation,2",
                    "https://loremflickr.com/800/600/microgrid,1",
                    "https://loremflickr.com/800/600/microgrid,2",
                    "https://loremflickr.com/800/600/village,electricity,1",
                    "https://loremflickr.com/800/600/village,electricity,2",
                    "https://loremflickr.com/800/600/engineer,work,1",
                    "https://loremflickr.com/800/600/engineer,work,2",
                    "https://loremflickr.com/800/600/solar,education,1",
                    "https://loremflickr.com/800/600/solar,education,2",
                    "https://loremflickr.com/800/600/panel,maintenance,1",
                    "https://loremflickr.com/800/600/panel,maintenance,2",
                    "https://loremflickr.com/800/600/solar,community,1",
                    "https://loremflickr.com/800/600/solar,community,2",
                    "https://loremflickr.com/800/600/renewable,energy,1",
                    "https://loremflickr.com/800/600/renewable,energy,2",
                    "https://loremflickr.com/800/600/installation,team,1",
                    "https://loremflickr.com/800/600/installation,team,2",
                    "https://loremflickr.com/800/600/solar,village,1",
                    "https://loremflickr.com/800/600/solar,village,2",
                    "https://loremflickr.com/800/600/panel,testing,1",
                    "https://loremflickr.com/800/600/panel,testing,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=kingslish_example_solar",
                ],
                "application_deadline": timezone.now() + timedelta(days=45),
                "start_date": timezone.now().date() + timedelta(days=60),
                "end_date": timezone.now().date() + timedelta(days=90),
                "is_featured": True,
            },
            {
                "title_en": "Cultural Exchange: Arts & Heritage Workshops",
                "teaser_en": "Support local artisans through arts workshops, cultural exchange, and documentation of heritage crafts.",
                "background_objectives_en": "Preserving traditional crafts and supporting artisans drives cultural resilience and livelihood improvements.",
                "tasks_eligibility_en": "Tasks: workshop facilitation, documentation. Eligibility: arts/cultural studies background desirable.",
                "country_en": "Indonesia",
                "theme_en": "Culture",

                "title_zh_tw": "文化交流：藝術與傳統工作坊",
                "teaser_zh_tw": "支持當地工匠，透過藝術工作坊、文化交流與傳統工藝紀錄。",
                "background_objectives_zh_tw": "保護傳統工藝並支持工匠，提升文化韌性與生計。",
                "tasks_eligibility_zh_tw": "任務：主持工作坊、紀錄工藝。資格：藝術或文化研究背景佳。",
                "country_zh_tw": "印尼",
                "theme_zh_tw": "文化",

                "kicc_project_id": "CUL-ID-005",
                "duration": 20,
                "difficulty": "Easy",
                "total_headcount": 20,
                "cover_image_url": "https://loremflickr.com/800/600/arts,crafts,heritage",
                "image_urls": [
                    "https://loremflickr.com/800/600/arts,crafts,1",
                    "https://loremflickr.com/800/600/arts,crafts,2",
                    "https://loremflickr.com/800/600/handicraft,1",
                    "https://loremflickr.com/800/600/handicraft,2",
                    "https://loremflickr.com/800/600/artisan,1",
                    "https://loremflickr.com/800/600/artisan,2",
                    "https://loremflickr.com/800/600/workshop,1",
                    "https://loremflickr.com/800/600/workshop,2",
                    "https://loremflickr.com/800/600/cultural,event,1",
                    "https://loremflickr.com/800/600/cultural,event,2",
                    "https://loremflickr.com/800/600/traditional,craft,1",
                    "https://loremflickr.com/800/600/traditional,craft,2",
                    "https://loremflickr.com/800/600/documentation,1",
                    "https://loremflickr.com/800/600/documentation,2",
                    "https://loremflickr.com/800/600/elderly,master,1",
                    "https://loremflickr.com/800/600/elderly,master,2",
                    "https://loremflickr.com/800/600/children,learn,1",
                    "https://loremflickr.com/800/600/children,learn,2",
                    "https://loremflickr.com/800/600/market,crafts,1",
                    "https://loremflickr.com/800/600/market,crafts,2",
                    "https://loremflickr.com/800/600/gallery,exhibition,1",
                    "https://loremflickr.com/800/600/gallery,exhibition,2",
                    "https://loremflickr.com/800/600/sketching,1",
                    "https://loremflickr.com/800/600/sketching,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=kingslish_example_arts",
                ],
                "application_deadline": timezone.now() + timedelta(days=40),
                "start_date": timezone.now().date() + timedelta(days=55),
                "end_date": timezone.now().date() + timedelta(days=65),
                "is_hero_highlight": False,
            },
            {
                "title_en": "Agriculture & Food Security Program",
                "teaser_en": "Help local farmers boost yields using improved methods and sustainable techniques.",
                "background_objectives_en": "Food security is critical to rural resilience; teaching sustainable agriculture helps reduce vulnerability.",
                "tasks_eligibility_en": "Tasks: demonstrate farming techniques, monitor yields. Eligibility: agriculture background preferred.",
                "country_en": "Nepal",
                "theme_en": "Agriculture",

                "title_zh_tw": "農業與糧食安全計畫",
                "teaser_zh_tw": "協助當地農民透過改良方法與永續技術提升產量。",
                "background_objectives_zh_tw": "糧食安全對於農村韌性至關重要；教授永續農業有助降低脆弱性。",
                "tasks_eligibility_zh_tw": "任務：示範耕作技術、監測產量。資格：農業背景佳。",
                "country_zh_tw": "尼泊爾",
                "theme_zh_tw": "農業",

                "kicc_project_id": "AGR-NP-006",
                "duration": 28,
                "difficulty": "Medium",
                "total_headcount": 18,
                "cover_image_url": "https://loremflickr.com/800/600/farming,terrace,nepal",
                "image_urls": [
                    "https://loremflickr.com/800/600/farming,1",
                    "https://loremflickr.com/800/600/farming,2",
                    "https://loremflickr.com/800/600/sustainable,agriculture,1",
                    "https://loremflickr.com/800/600/sustainable,agriculture,2",
                    "https://loremflickr.com/800/600/terrace,farm,1",
                    "https://loremflickr.com/800/600/terrace,farm,2",
                    "https://loremflickr.com/800/600/soil,testing,1",
                    "https://loremflickr.com/800/600/soil,testing,2",
                    "https://loremflickr.com/800/600/irrigation,1",
                    "https://loremflickr.com/800/600/irrigation,2",
                    "https://loremflickr.com/800/600/market,outlet,1",
                    "https://loremflickr.com/800/600/market,outlet,2",
                    "https://loremflickr.com/800/600/crop,rotation,1",
                    "https://loremflickr.com/800/600/crop,rotation,2",
                    "https://loremflickr.com/800/600/seed,distribution,1",
                    "https://loremflickr.com/800/600/seed,distribution,2",
                    "https://loremflickr.com/800/600/community,training,1",
                    "https://loremflickr.com/800/600/community,training,2",
                    "https://loremflickr.com/800/600/tractor,work,1",
                    "https://loremflickr.com/800/600/tractor,work,2",
                    "https://loremflickr.com/800/600/agronomy,1",
                    "https://loremflickr.com/800/600/agronomy,2",
                    "https://loremflickr.com/800/600/food,security,1",
                    "https://loremflickr.com/800/600/food,security,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=kingslish_example_agriculture",
                ],
                "application_deadline": timezone.now() + timedelta(days=60),
                "start_date": timezone.now().date() + timedelta(days=75),
                "end_date": timezone.now().date() + timedelta(days=100),
                "is_featured": False,
            },
            {
                "title_en": "Women's Empowerment & Livelihood Training",
                "teaser_en": "Facilitate skill training and microenterprise support to boost women's livelihood options.",
                "background_objectives_en": "Empowered women contribute to resilient households; our workshops provide skills and market access support.",
                "tasks_eligibility_en": "Tasks: run skills workshops, mentoring. Eligibility: community facilitation background preferred.",
                "country_en": "Myanmar",
                "theme_en": "Economic Development",

                "title_zh_tw": "婦女賦權與生計培訓",
                "teaser_zh_tw": "舉辦技能訓練與小型企業支持，提升婦女生計選擇。",
                "background_objectives_zh_tw": "賦權婦女可提升家庭韌性；我們的工作坊提供技能與市場支持。",
                "tasks_eligibility_zh_tw": "任務：主持技能工作坊、提供指導。資格：具社區輔導背景者優先。",
                "country_zh_tw": "緬甸",
                "theme_zh_tw": "經濟發展",

                "kicc_project_id": "ECO-MM-007",
                "duration": 22,
                "difficulty": "Easy",
                "total_headcount": 25,
                "cover_image_url": "https://loremflickr.com/800/600/women,training,livelihood",
                "image_urls": [
                    "https://loremflickr.com/800/600/women,training,1",
                    "https://loremflickr.com/800/600/women,training,2",
                    "https://loremflickr.com/800/600/microenterprise,1",
                    "https://loremflickr.com/800/600/microenterprise,2",
                    "https://loremflickr.com/800/600/sewing,stitching,1",
                    "https://loremflickr.com/800/600/sewing,stitching,2",
                    "https://loremflickr.com/800/600/market,access,1",
                    "https://loremflickr.com/800/600/market,access,2",
                    "https://loremflickr.com/800/600/mentorship,1",
                    "https://loremflickr.com/800/600/mentorship,2",
                    "https://loremflickr.com/800/600/entrepreneur,1",
                    "https://loremflickr.com/800/600/entrepreneur,2",
                    "https://loremflickr.com/800/600/skill,training,1",
                    "https://loremflickr.com/800/600/skill,training,2",
                    "https://loremflickr.com/800/600/community,support,1",
                    "https://loremflickr.com/800/600/community,support,2",
                    "https://loremflickr.com/800/600/fair,trade,1",
                    "https://loremflickr.com/800/600/fair,trade,2",
                    "https://loremflickr.com/800/600/bazaar,1",
                    "https://loremflickr.com/800/600/bazaar,2",
                    "https://loremflickr.com/800/600/female,entrepreneur,1",
                    "https://loremflickr.com/800/600/female,entrepreneur,2",
                    "https://loremflickr.com/800/600/handicraft,production,1",
                    "https://loremflickr.com/800/600/handicraft,production,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=kingslish_example_empower",
                ],
                "application_deadline": timezone.now() + timedelta(days=20),
                "start_date": timezone.now().date() + timedelta(days=27),
                "end_date": timezone.now().date() + timedelta(days=40),
                "is_featured": False,
            },
            {
                # English
                "title_en": "Marine Conservation & Beach Cleanup",
                "teaser_en": "Join us in preserving marine life by keeping our coastlines clean and plastic-free.",
                "background_objectives_en": "Plastic pollution threatens marine biodiversity. We aim to remove 5 tons of waste.",
                "tasks_eligibility_en": "Tasks: Collecting waste, sorting recyclables. Eligibility: Physical fitness.",
                "country_en": "Philippines",
                "theme_en": "Environment",

                # Traditional Chinese (ZH-TW)
                "title_zh_tw": "海洋保育與海灘清潔",
                "teaser_zh_tw": "加入我們，透過保持海岸線清潔和無塑化來保護海洋生物。",
                "background_objectives_zh_tw": "塑膠污染威脅海洋生物多樣性。我們的目標是清除5噸垃圾。",
                "tasks_eligibility_zh_tw": "任務：收集垃圾、分類回收物。資格：身體健康。",
                "country_zh_tw": "菲律賓",
                "theme_zh_tw": "環境",

                # Metadata & Media
                "kicc_project_id": "ENV-PH-002",
                "duration": 25,
                "difficulty": "Easy",
                "total_headcount": 50,
                
                # Images via Lorem Flickr
                "cover_image_url": "https://loremflickr.com/800/600/beach,cleanup,ocean",
                "image_urls": [
                    "https://loremflickr.com/800/600/plastic,recycle,1",
                    "https://loremflickr.com/800/600/plastic,recycle,2",
                    "https://loremflickr.com/800/600/sea,turtle,nature,1",
                    "https://loremflickr.com/800/600/sea,turtle,nature,2",
                    "https://loremflickr.com/800/600/volunteers,sand,1",
                    "https://loremflickr.com/800/600/volunteers,sand,2",
                    "https://loremflickr.com/800/600/beach,cleanup,1",
                    "https://loremflickr.com/800/600/beach,cleanup,2",
                    "https://loremflickr.com/800/600/trash,collection,1",
                    "https://loremflickr.com/800/600/trash,collection,2",
                    "https://loremflickr.com/800/600/sea,life,1",
                    "https://loremflickr.com/800/600/sea,life,2",
                    "https://loremflickr.com/800/600/recycling,sort,1",
                    "https://loremflickr.com/800/600/recycling,sort,2",
                    "https://loremflickr.com/800/600/volunteer,team,1",
                    "https://loremflickr.com/800/600/volunteer,team,2",
                    "https://loremflickr.com/800/600/education,beach,1",
                    "https://loremflickr.com/800/600/education,beach,2",
                    "https://loremflickr.com/800/600/sea,birds,1",
                    "https://loremflickr.com/800/600/sea,birds,2",
                    "https://loremflickr.com/800/600/plastic,bales,1",
                    "https://loremflickr.com/800/600/plastic,bales,2",
                    "https://loremflickr.com/800/600/community,cleanup,1",
                    "https://loremflickr.com/800/600/community,cleanup,2",
                ],
                
                # Videos from Kingslish App Channel
                "video_urls": [
                     "https://www.youtube.com/@kingslishapp/videos"
                ],

                "application_deadline": timezone.now() + timedelta(days=15),
                "start_date": timezone.now().date() + timedelta(days=20),
                "end_date": timezone.now().date() + timedelta(days=25),
                "is_hero_highlight": True,
            },
            {
                "title_en": "Water Well Construction & Sanitation",
                "teaser_en": "Build and maintain water wells to provide clean drinking water to rural communities.",
                "background_objectives_en": "Clean water is essential; we aim to construct 5 wells and educate on water safety.",
                "tasks_eligibility_en": "Tasks: Well construction, hygiene training. Eligibility: Construction experience helpful.",
                "country_en": "Ghana",
                "theme_en": "Water & Sanitation",
                "title_zh_tw": "水井建設與衛生",
                "teaser_zh_tw": "為農村社區建設和維護水井，提供乾淨飲用水。",
                "background_objectives_zh_tw": "乾淨水源至關重要；我們的目標是建造5口井並教授水安全。",
                "tasks_eligibility_zh_tw": "任務：井水建設、衛生培訓。資格：建築經驗有幫助。",
                "country_zh_tw": "加納",
                "theme_zh_tw": "水與衛生",
                "kicc_project_id": "WTR-GH-008",
                "duration": 35,
                "difficulty": "Hard",
                "total_headcount": 15,
                "cover_image_url": "https://loremflickr.com/800/600/water,well,construction",
                "image_urls": [
                    "https://loremflickr.com/800/600/water,well,1",
                    "https://loremflickr.com/800/600/water,well,2",
                    "https://loremflickr.com/800/600/construction,team,1",
                    "https://loremflickr.com/800/600/construction,team,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=Cr7Se5revOk",
                    "https://www.youtube.com/watch?v=5U9DLtSwNgQ"
                ],
                "application_deadline": timezone.now() + timedelta(days=50),
                "start_date": timezone.now().date() + timedelta(days=65),
                "end_date": timezone.now().date() + timedelta(days=85),
                "is_featured": True,
            },
            {
                "title_en": "Community Library Development",
                "teaser_en": "Establish and organize community libraries to improve literacy and learning access.",
                "background_objectives_en": "Limited book access hinders learning; we create libraries and train librarians.",
                "tasks_eligibility_en": "Tasks: Library setup, cataloging. Eligibility: Organizational skills.",
                "country_en": "Kenya",
                "theme_en": "Education",
                "title_zh_tw": "社區圖書館發展",
                "teaser_zh_tw": "建立和組織社區圖書館，提高識字率和學習機會。",
                "background_objectives_zh_tw": "書籍獲取受限會阻礙學習；我們建立圖書館並培訓圖書館員。",
                "tasks_eligibility_zh_tw": "任務：圖書館設置、編目。資格：組織能力強。",
                "country_zh_tw": "肯亞",
                "theme_zh_tw": "教育",
                "kicc_project_id": "EDU-KE-009",
                "duration": 18,
                "difficulty": "Easy",
                "total_headcount": 20,
                "cover_image_url": "https://loremflickr.com/800/600/library,books,community",
                "image_urls": [
                    "https://loremflickr.com/800/600/library,books,1",
                    "https://loremflickr.com/800/600/library,books,2",
                    "https://loremflickr.com/800/600/reading,children,1",
                    "https://loremflickr.com/800/600/reading,children,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=0x5N_7d82JY",
                    "https://www.youtube.com/watch?v=LYowTbsj8Zs"
                ],
                "application_deadline": timezone.now() + timedelta(days=25),
                "start_date": timezone.now().date() + timedelta(days=35),
                "end_date": timezone.now().date() + timedelta(days=45),
                "is_featured": False,
            },
            {
                "title_en": "Disaster Risk Reduction Training",
                "teaser_en": "Train communities on disaster preparedness and emergency response procedures.",
                "background_objectives_en": "Vulnerable communities need disaster awareness; we provide training and resources.",
                "tasks_eligibility_en": "Tasks: Training facilitation, resource prep. Eligibility: Risk management experience.",
                "country_en": "Bangladesh",
                "theme_en": "Disaster Management",
                "title_zh_tw": "災害風險降低培訓",
                "teaser_zh_tw": "培訓社區應對災害的準備和應急程序。",
                "background_objectives_zh_tw": "脆弱社區需要災害意識；我們提供培訓和資源。",
                "tasks_eligibility_zh_tw": "任務：培訓促進、資源準備。資格：具風險管理經驗。",
                "country_zh_tw": "孟加拉",
                "theme_zh_tw": "災害管理",
                "kicc_project_id": "DSR-BD-010",
                "duration": 32,
                "difficulty": "Medium",
                "total_headcount": 40,
                "cover_image_url": "https://loremflickr.com/800/600/disaster,preparedness,training",
                "image_urls": [
                    "https://loremflickr.com/800/600/disaster,training,1",
                    "https://loremflickr.com/800/600/disaster,training,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=2---xb-BmBw",
                    "https://www.youtube.com/watch?v=KaWQ2Ua9CW8"
                ],
                "application_deadline": timezone.now() + timedelta(days=35),
                "start_date": timezone.now().date() + timedelta(days=48),
                "end_date": timezone.now().date() + timedelta(days=68),
                "is_featured": False,
            },
            {
                "title_en": "Renewable Energy: Biogas Production",
                "teaser_en": "Install biogas systems using agricultural waste to provide sustainable cooking fuel.",
                "background_objectives_en": "Biogas reduces deforestation and provides clean cooking fuel.",
                "tasks_eligibility_en": "Tasks: System installation, user training. Eligibility: Technical aptitude.",
                "country_en": "Tanzania",
                "theme_en": "Energy",
                "title_zh_tw": "再生能源：生物氣生產",
                "teaser_zh_tw": "使用農業廢棄物安裝生物氣系統，提供永續烹飪燃料。",
                "background_objectives_zh_tw": "生物氣減少森林砍伐並提供清潔烹飪燃料。",
                "tasks_eligibility_zh_tw": "任務：系統安裝、用戶培訓。資格：技術能力強。",
                "country_zh_tw": "坦尚尼亞",
                "theme_zh_tw": "能源",
                "kicc_project_id": "ENE-TZ-011",
                "duration": 27,
                "difficulty": "Medium",
                "total_headcount": 12,
                "cover_image_url": "https://loremflickr.com/800/600/biogas,renewable,energy",
                "image_urls": [
                    "https://loremflickr.com/800/600/biogas,system,1",
                    "https://loremflickr.com/800/600/biogas,system,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=BU1TQY-SfkA",
                    "https://www.youtube.com/watch?v=B0iwi5EXFWU"
                ],
                "application_deadline": timezone.now() + timedelta(days=42),
                "start_date": timezone.now().date() + timedelta(days=56),
                "end_date": timezone.now().date() + timedelta(days=78),
                "is_featured": True,
            },
            {
                "title_en": "Youth Tech Skills Training",
                "teaser_en": "Teach digital literacy and coding to youth in underserved communities.",
                "background_objectives_en": "Tech skills open career opportunities; we offer coding and digital literacy courses.",
                "tasks_eligibility_en": "Tasks: Teaching coding, mentoring. Eligibility: Tech background required.",
                "country_en": "Sri Lanka",
                "theme_en": "Education",
                "title_zh_tw": "青年科技技能培訓",
                "teaser_zh_tw": "為服務欠缺社區的青年教授數位識字和編碼。",
                "background_objectives_zh_tw": "科技技能開啟職業機會；我們提供編碼和數位識字課程。",
                "tasks_eligibility_zh_tw": "任務：教授編碼、提供指導。資格：需要技術背景。",
                "country_zh_tw": "斯里蘭卡",
                "theme_zh_tw": "教育",
                "kicc_project_id": "EDU-LK-012",
                "duration": 25,
                "difficulty": "Medium",
                "total_headcount": 30,
                "cover_image_url": "https://loremflickr.com/800/600/coding,computer,training",
                "image_urls": [
                    "https://loremflickr.com/800/600/computer,class,1",
                    "https://loremflickr.com/800/600/computer,class,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=Kd45fA5pD9I",
                    "https://www.youtube.com/watch?v=J_kcp_Owsrk"
                ],
                "application_deadline": timezone.now() + timedelta(days=28),
                "start_date": timezone.now().date() + timedelta(days=38),
                "end_date": timezone.now().date() + timedelta(days=55),
                "is_featured": False,
            },
            {
                "title_en": "Mental Health & Wellness Program",
                "teaser_en": "Introduce mental health awareness and peer support systems to communities.",
                "background_objectives_en": "Mental health stigma is high; we build awareness and support networks.",
                "tasks_eligibility_en": "Tasks: Training workshops, peer support. Eligibility: Psychology or counseling background.",
                "country_en": "Pakistan",
                "theme_en": "Health",
                "title_zh_tw": "心理健康與健康計畫",
                "teaser_zh_tw": "向社區介紹心理健康意識和同伴支持系統。",
                "background_objectives_zh_tw": "心理健康污名很高；我們建立意識和支持網絡。",
                "tasks_eligibility_zh_tw": "任務：培訓工作坊、同伴支持。資格：心理或諮詢背景。",
                "country_zh_tw": "巴基斯坦",
                "theme_zh_tw": "健康",
                "kicc_project_id": "HLT-PK-013",
                "duration": 20,
                "difficulty": "Medium",
                "total_headcount": 25,
                "cover_image_url": "https://loremflickr.com/800/600/mental,health,wellness",
                "image_urls": [
                    "https://loremflickr.com/800/600/wellness,support,1",
                    "https://loremflickr.com/800/600/wellness,support,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=tYANvrEzvKk",
                    "https://www.youtube.com/watch?v=xJl9i6nsmvw"
                ],
                "application_deadline": timezone.now() + timedelta(days=22),
                "start_date": timezone.now().date() + timedelta(days=32),
                "end_date": timezone.now().date() + timedelta(days=48),
                "is_featured": False,
            },
            {
                "title_en": "Reforestation & Forest Management",
                "teaser_en": "Plant trees and restore degraded forests while educating on forest conservation.",
                "background_objectives_en": "Deforestation drives climate change; we plant 10,000 trees and build management plans.",
                "tasks_eligibility_en": "Tasks: Tree planting, site management. Eligibility: Outdoor work capability.",
                "country_en": "Uganda",
                "theme_en": "Environment",
                "title_zh_tw": "重新造林與森林管理",
                "teaser_zh_tw": "種植樹木並恢復退化森林，同時教授森林保護。",
                "background_objectives_zh_tw": "森林砍伐加劇氣候變化；我們種植10,000棵樹並制定管理計劃。",
                "tasks_eligibility_zh_tw": "任務：種植樹木、場地管理。資格：具戶外工作能力。",
                "country_zh_tw": "烏干達",
                "theme_zh_tw": "環境",
                "kicc_project_id": "ENV-UG-014",
                "duration": 42,
                "difficulty": "Medium",
                "total_headcount": 35,
                "cover_image_url": "https://loremflickr.com/800/600/reforestation,trees,forest",
                "image_urls": [
                    "https://loremflickr.com/800/600/forest,planting,1",
                    "https://loremflickr.com/800/600/forest,planting,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=us7SMS44FIw",
                    "https://www.youtube.com/watch?v=w1EXAdzDAxA"
                ],
                "application_deadline": timezone.now() + timedelta(days=55),
                "start_date": timezone.now().date() + timedelta(days=70),
                "end_date": timezone.now().date() + timedelta(days=105),
                "is_hero_highlight": True,
            },
            {
                "title_en": "Maternal & Child Health Program",
                "teaser_en": "Improve maternal and child healthcare through training and resource provision.",
                "background_objectives_en": "Maternal mortality is high in developing countries; we provide training and supplies.",
                "tasks_eligibility_en": "Tasks: Health training, resource distribution. Eligibility: Health/nursing background.",
                "country_en": "Mali",
                "theme_en": "Health",
                "title_zh_tw": "孕產婦與兒童衛生計畫",
                "teaser_zh_tw": "透過培訓和資源提供改善孕產婦和兒童衛生保健。",
                "background_objectives_zh_tw": "孕產婦死亡率在發展中國家很高；我們提供培訓和物資。",
                "tasks_eligibility_zh_tw": "任務：衛生培訓、資源分配。資格：衛生或護理背景。",
                "country_zh_tw": "馬里",
                "theme_zh_tw": "健康",
                "kicc_project_id": "HLT-ML-015",
                "duration": 38,
                "difficulty": "Hard",
                "total_headcount": 20,
                "cover_image_url": "https://loremflickr.com/800/600/maternal,child,health",
                "image_urls": [
                    "https://loremflickr.com/800/600/child,health,1",
                    "https://loremflickr.com/800/600/child,health,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=DSBcBSdJDaE",
                    "https://www.youtube.com/watch?v=PhJnZnQuuT0"
                ],
                "application_deadline": timezone.now() + timedelta(days=60),
                "start_date": timezone.now().date() + timedelta(days=75),
                "end_date": timezone.now().date() + timedelta(days=105),
                "is_featured": True,
            },
            {
                "title_en": "Education Infrastructure Development",
                "teaser_en": "Build and renovate school facilities to improve learning environments.",
                "background_objectives_en": "Poor infrastructure limits learning; we construct classrooms and renovate facilities.",
                "tasks_eligibility_en": "Tasks: Construction, facility management. Eligibility: Building skills.",
                "country_en": "Mozambique",
                "theme_en": "Education",
                "title_zh_tw": "教育基礎設施發展",
                "teaser_zh_tw": "建設和翻新學校設施以改善學習環境。",
                "background_objectives_zh_tw": "基礎設施差會限制學習；我們建造教室並翻新設施。",
                "tasks_eligibility_zh_tw": "任務：建設、設施管理。資格：建築技能。",
                "country_zh_tw": "莫桑比克",
                "theme_zh_tw": "教育",
                "kicc_project_id": "EDU-MZ-016",
                "duration": 50,
                "difficulty": "Hard",
                "total_headcount": 25,
                "cover_image_url": "https://loremflickr.com/800/600/school,building,construction",
                "image_urls": [
                    "https://loremflickr.com/800/600/school,construction,1",
                    "https://loremflickr.com/800/600/school,construction,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=ywVS21j7fE8",
                    "https://www.youtube.com/watch?v=4l4UWZGxvoc"
                ],
                "application_deadline": timezone.now() + timedelta(days=70),
                "start_date": timezone.now().date() + timedelta(days=85),
                "end_date": timezone.now().date() + timedelta(days=125),
                "is_featured": False,
            },
            {
                "title_en": "Clean Cooking Solutions",
                "teaser_en": "Promote and distribute clean cooking stoves to reduce indoor air pollution.",
                "background_objectives_en": "Indoor air pollution from cooking fires kills millions; we distribute clean stoves.",
                "tasks_eligibility_en": "Tasks: Stove installation, health education. Eligibility: Manual skills.",
                "country_en": "Ethiopia",
                "theme_en": "Health & Energy",
                "title_zh_tw": "清潔烹飪解決方案",
                "teaser_zh_tw": "推廣和分發清潔烹飪爐灶以減少室內空氣污染。",
                "background_objectives_zh_tw": "烹飪火災導致的室內空氣污染造成數百萬人死亡；我們分發清潔爐灶。",
                "tasks_eligibility_zh_tw": "任務：爐灶安裝、衛生教育。資格：手工技能。",
                "country_zh_tw": "衣索比亞",
                "theme_zh_tw": "衛生與能源",
                "kicc_project_id": "HLT-ET-017",
                "duration": 24,
                "difficulty": "Easy",
                "total_headcount": 40,
                "cover_image_url": "https://loremflickr.com/800/600/clean,stove,cooking",
                "image_urls": [
                    "https://loremflickr.com/800/600/cooking,stove,1",
                    "https://loremflickr.com/800/600/cooking,stove,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=R-FhDcKJFqw",
                    "https://www.youtube.com/watch?v=7wDTkAiaNyc"
                ],
                "application_deadline": timezone.now() + timedelta(days=18),
                "start_date": timezone.now().date() + timedelta(days=26),
                "end_date": timezone.now().date() + timedelta(days=42),
                "is_featured": False,
            },
            {
                "title_en": "Sports for Youth Development",
                "teaser_en": "Use sports to build life skills and promote youth leadership.",
                "background_objectives_en": "Sports programs engage at-risk youth and teach leadership; we organize tournaments.",
                "tasks_eligibility_en": "Tasks: Sports coaching, youth mentoring. Eligibility: Sports background.",
                "country_en": "Zambia",
                "theme_en": "Youth Development",
                "title_zh_tw": "青年體育發展",
                "teaser_zh_tw": "利用體育建設生活技能並促進青年領導。",
                "background_objectives_zh_tw": "運動計畫吸引高風險青年並教授領導力；我們組織錦標賽。",
                "tasks_eligibility_zh_tw": "任務：體育教練、青年指導。資格：運動背景。",
                "country_zh_tw": "贊比亞",
                "theme_zh_tw": "青年發展",
                "kicc_project_id": "YTH-ZM-018",
                "duration": 26,
                "difficulty": "Easy",
                "total_headcount": 45,
                "cover_image_url": "https://loremflickr.com/800/600/youth,sports,development",
                "image_urls": [
                    "https://loremflickr.com/800/600/sports,youth,1",
                    "https://loremflickr.com/800/600/sports,youth,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=ZpmxwtN4KRA",
                    "https://www.youtube.com/watch?v=Scg3HjVHOBI"
                ],
                "application_deadline": timezone.now() + timedelta(days=30),
                "start_date": timezone.now().date() + timedelta(days=40),
                "end_date": timezone.now().date() + timedelta(days=60),
                "is_featured": True,
            },
            {
                "title_en": "Skills for Persons with Disabilities",
                "teaser_en": "Provide inclusive vocational training for persons with disabilities.",
                "background_objectives_en": "PWD often excluded from opportunities; we offer vocational skills and job placement.",
                "tasks_eligibility_en": "Tasks: Skills training, job placement support. Eligibility: Inclusive education approach.",
                "country_en": "Rwanda",
                "theme_en": "Inclusive Development",
                "title_zh_tw": "身心障礙人士技能培訓",
                "teaser_zh_tw": "為身心障礙人士提供包容性職業培訓。",
                "background_objectives_zh_tw": "身心障礙者常被排除在機會之外；我們提供職業技能和工作安置。",
                "tasks_eligibility_zh_tw": "任務：技能培訓、工作安置支持。資格：包容性教育方法。",
                "country_zh_tw": "盧安達",
                "theme_zh_tw": "包容性發展",
                "kicc_project_id": "INC-RW-019",
                "duration": 28,
                "difficulty": "Medium",
                "total_headcount": 30,
                "cover_image_url": "https://loremflickr.com/800/600/disability,skills,training",
                "image_urls": [
                    "https://loremflickr.com/800/600/inclusive,skills,1",
                    "https://loremflickr.com/800/600/inclusive,skills,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=g3G9dCECYGU",
                    "https://www.youtube.com/watch?v=Nj4O3BazlWk"
                ],
                "application_deadline": timezone.now() + timedelta(days=35),
                "start_date": timezone.now().date() + timedelta(days=46),
                "end_date": timezone.now().date() + timedelta(days=68),
                "is_featured": False,
            },
            {
                "title_en": "HIV/AIDS Awareness & Prevention",
                "teaser_en": "Deliver education on HIV/AIDS prevention, testing, and treatment access.",
                "background_objectives_en": "Stigma and misinformation hinder prevention; we provide education and support.",
                "tasks_eligibility_en": "Tasks: Education delivery, resource provision. Eligibility: Health background.",
                "country_en": "South Africa",
                "theme_en": "Health",
                "title_zh_tw": "愛滋病毒／愛滋病意識與預防",
                "teaser_zh_tw": "提供愛滋病毒／愛滋病預防、檢測和治療獲取教育。",
                "background_objectives_zh_tw": "污名和錯誤訊息阻礙預防；我們提供教育和支持。",
                "tasks_eligibility_zh_tw": "任務：教育傳遞、資源提供。資格：衛生背景。",
                "country_zh_tw": "南非",
                "theme_zh_tw": "健康",
                "kicc_project_id": "HLT-ZA-020",
                "duration": 31,
                "difficulty": "Medium",
                "total_headcount": 35,
                "cover_image_url": "https://loremflickr.com/800/600/hiv,awareness,prevention",
                "image_urls": [
                    "https://loremflickr.com/800/600/health,awareness,1",
                    "https://loremflickr.com/800/600/health,awareness,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=iv6052eJ6I8",
                    "https://www.youtube.com/watch?v=a8DueDYaxvE"
                ],
                "application_deadline": timezone.now() + timedelta(days=40),
                "start_date": timezone.now().date() + timedelta(days=52),
                "end_date": timezone.now().date() + timedelta(days=76),
                "is_featured": True,
            },
            {
                "title_en": "Microfinance & Business Development",
                "teaser_en": "Establish microfinance groups and provide business development training.",
                "background_objectives_en": "Lack of capital limits entrepreneurship; we provide finance and training.",
                "tasks_eligibility_en": "Tasks: Business training, group facilitation. Eligibility: Finance background.",
                "country_en": "Malawi",
                "theme_en": "Economic Development",
                "title_zh_tw": "小額融資與業務發展",
                "teaser_zh_tw": "建立小額融資群組並提供業務發展培訓。",
                "background_objectives_zh_tw": "資本短缺限制創業；我們提供融資和培訓。",
                "tasks_eligibility_zh_tw": "任務：業務培訓、小組協調。資格：融資背景。",
                "country_zh_tw": "馬拉威",
                "theme_zh_tw": "經濟發展",
                "kicc_project_id": "ECO-MW-021",
                "duration": 30,
                "difficulty": "Medium",
                "total_headcount": 28,
                "cover_image_url": "https://loremflickr.com/800/600/microfinance,business,training",
                "image_urls": [
                    "https://loremflickr.com/800/600/business,training,1",
                    "https://loremflickr.com/800/600/business,training,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=o7O0Smy3jPo",
                    "https://www.youtube.com/watch?v=PzrEoE8AU3c"
                ],
                "application_deadline": timezone.now() + timedelta(days=45),
                "start_date": timezone.now().date() + timedelta(days=58),
                "end_date": timezone.now().date() + timedelta(days=80),
                "is_featured": False,
            },
            {
                "title_en": "Language & Literacy Program",
                "teaser_en": "Teach local languages and literacy skills to marginalized groups.",
                "background_objectives_en": "Language barriers hinder education; we teach mother-tongue literacy.",
                "tasks_eligibility_en": "Tasks: Language teaching, literacy instruction. Eligibility: Language expertise.",
                "country_en": "Bolivia",
                "theme_en": "Education",
                "title_zh_tw": "語言與識字計畫",
                "teaser_zh_tw": "教授當地語言和識字技能給邊緣化群體。",
                "background_objectives_zh_tw": "語言障礙阻礙教育；我們教授母語識字。",
                "tasks_eligibility_zh_tw": "任務：語言教學、識字教學。資格：語言專業知識。",
                "country_zh_tw": "玻利維亞",
                "theme_zh_tw": "教育",
                "kicc_project_id": "EDU-BO-022",
                "duration": 26,
                "difficulty": "Easy",
                "total_headcount": 32,
                "cover_image_url": "https://loremflickr.com/800/600/language,literacy,education",
                "image_urls": [
                    "https://loremflickr.com/800/600/literacy,class,1",
                    "https://loremflickr.com/800/600/literacy,class,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=_s9JzPWDcIc",
                    "https://www.youtube.com/watch?v=i-lrDYV_piE"
                ],
                "application_deadline": timezone.now() + timedelta(days=32),
                "start_date": timezone.now().date() + timedelta(days=44),
                "end_date": timezone.now().date() + timedelta(days=62),
                "is_featured": False,
            },
            {
                "title_en": "Climate Change & Adaptation",
                "teaser_en": "Help communities adapt to climate change through sustainable practices.",
                "background_objectives_en": "Climate impacts threaten livelihoods; we teach adaptation strategies.",
                "tasks_eligibility_en": "Tasks: Training, adaptation planning. Eligibility: Environmental science background.",
                "country_en": "Honduras",
                "theme_en": "Environment",
                "title_zh_tw": "氣候變遷與適應",
                "teaser_zh_tw": "透過永續實踐幫助社區適應氣候變化。",
                "background_objectives_zh_tw": "氣候影響威脅生計；我們教授適應戰略。",
                "tasks_eligibility_zh_tw": "任務：培訓、適應規劃。資格：環境科學背景。",
                "country_zh_tw": "宏都拉斯",
                "theme_zh_tw": "環境",
                "kicc_project_id": "ENV-HN-023",
                "duration": 35,
                "difficulty": "Medium",
                "total_headcount": 26,
                "cover_image_url": "https://loremflickr.com/800/600/climate,adaptation,sustainability",
                "image_urls": [
                    "https://loremflickr.com/800/600/climate,adaptation,1",
                    "https://loremflickr.com/800/600/climate,adaptation,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=xaaiy2KcLkQ",
                    "https://www.youtube.com/watch?v=4ORYxFFs_oU"
                ],
                "application_deadline": timezone.now() + timedelta(days=50),
                "start_date": timezone.now().date() + timedelta(days=64),
                "end_date": timezone.now().date() + timedelta(days=90),
                "is_featured": True,
            },
            {
                "title_en": "Food Processing & Nutrition",
                "teaser_en": "Teach food preservation and nutrition to improve food security.",
                "background_objectives_en": "Food losses reduce income; we teach preservation and nutrition.",
                "tasks_eligibility_en": "Tasks: Training, equipment setup. Eligibility: Food science/agriculture background.",
                "country_en": "Senegal",
                "theme_en": "Food Security",
                "title_zh_tw": "食品加工與營養",
                "teaser_zh_tw": "教授食品保存和營養以改善糧食安全。",
                "background_objectives_zh_tw": "食品損失減少收入；我們教授保存和營養。",
                "tasks_eligibility_zh_tw": "任務：培訓、設備設置。資格：食品科學或農業背景。",
                "country_zh_tw": "塞內加爾",
                "theme_zh_tw": "糧食安全",
                "kicc_project_id": "FSC-SN-024",
                "duration": 29,
                "difficulty": "Medium",
                "total_headcount": 24,
                "cover_image_url": "https://loremflickr.com/800/600/food,processing,nutrition",
                "image_urls": [
                    "https://loremflickr.com/800/600/food,processing,1",
                    "https://loremflickr.com/800/600/food,processing,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=RbgBNE_G5pE",
                    "https://www.youtube.com/watch?v=AZfHFDJuVak"
                ],
                "application_deadline": timezone.now() + timedelta(days=38),
                "start_date": timezone.now().date() + timedelta(days=50),
                "end_date": timezone.now().date() + timedelta(days=71),
                "is_featured": False,
            },
            {
                "title_en": "Conflict Resolution & Peace Building",
                "teaser_en": "Train community leaders in conflict resolution and peace-building.",
                "background_objectives_en": "Conflicts limit development; we teach mediation and dialogue.",
                "tasks_eligibility_en": "Tasks: Training facilitation, peace building. Eligibility: Conflict resolution experience.",
                "country_en": "South Sudan",
                "theme_en": "Peace & Security",
                "title_zh_tw": "衝突解決與和平建設",
                "teaser_zh_tw": "培訓社區領袖進行衝突解決和和平建設。",
                "background_objectives_zh_tw": "衝突限制發展；我們教授調解和對話。",
                "tasks_eligibility_zh_tw": "任務：培訓促進、和平建設。資格：衝突解決經驗。",
                "country_zh_tw": "南蘇丹",
                "theme_zh_tw": "和平與安全",
                "kicc_project_id": "PCE-SS-025",
                "duration": 33,
                "difficulty": "Hard",
                "total_headcount": 22,
                "cover_image_url": "https://loremflickr.com/800/600/peace,building,community",
                "image_urls": [
                    "https://loremflickr.com/800/600/peace,building,1",
                    "https://loremflickr.com/800/600/peace,building,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=ZRQYJucDSXM",
                    "https://www.youtube.com/watch?v=H-aBNHNB_6Y"
                ],
                "application_deadline": timezone.now() + timedelta(days=55),
                "start_date": timezone.now().date() + timedelta(days=70),
                "end_date": timezone.now().date() + timedelta(days=95),
                "is_featured": True,
            },
            {
                "title_en": "Water Harvesting & Management",
                "teaser_en": "Install rainwater harvesting systems and teach water management.",
                "background_objectives_en": "Water scarcity affects agriculture; we build reservoirs and train users.",
                "tasks_eligibility_en": "Tasks: System installation, user training. Eligibility: Engineering/agricultural background.",
                "country_en": "Namibia",
                "theme_en": "Water & Environment",
                "title_zh_tw": "集水與水資源管理",
                "teaser_zh_tw": "安裝雨水集集系統並教授水資源管理。",
                "background_objectives_zh_tw": "水資源短缺影響農業；我們建造水庫並訓練用戶。",
                "tasks_eligibility_zh_tw": "任務：系統安裝、用戶培訓。資格：工程或農業背景。",
                "country_zh_tw": "納米比亞",
                "theme_zh_tw": "水與環境",
                "kicc_project_id": "WTR-NA-026",
                "duration": 37,
                "difficulty": "Medium",
                "total_headcount": 18,
                "cover_image_url": "https://loremflickr.com/800/600/water,harvesting,management",
                "image_urls": [
                    "https://loremflickr.com/800/600/water,harvesting,1",
                    "https://loremflickr.com/800/600/water,harvesting,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=uOwNq-Nm-NU",
                    "https://www.youtube.com/watch?v=W8894gV6ArY"
                ],
                "application_deadline": timezone.now() + timedelta(days=48),
                "start_date": timezone.now().date() + timedelta(days=62),
                "end_date": timezone.now().date() + timedelta(days=88),
                "is_featured": False,
            },
            {
                "title_en": "Child Protection & Safeguarding",
                "teaser_en": "Establish child protection systems and provide safeguarding training.",
                "background_objectives_en": "Child abuse is widespread; we train communities and build protection systems.",
                "tasks_eligibility_en": "Tasks: Training, system development. Eligibility: Child welfare background.",
                "country_en": "Sierra Leone",
                "theme_en": "Child Welfare",
                "title_zh_tw": "兒童保護與保障",
                "teaser_zh_tw": "建立兒童保護系統並提供保障培訓。",
                "background_objectives_zh_tw": "兒童虐待廣泛存在；我們訓練社區並建立保護系統。",
                "tasks_eligibility_zh_tw": "任務：培訓、系統開發。資格：兒童福利背景。",
                "country_zh_tw": "獅子山",
                "theme_zh_tw": "兒童福利",
                "kicc_project_id": "CWL-SL-027",
                "duration": 27,
                "difficulty": "Medium",
                "total_headcount": 28,
                "cover_image_url": "https://loremflickr.com/800/600/child,protection,safeguarding",
                "image_urls": [
                    "https://loremflickr.com/800/600/child,safety,1",
                    "https://loremflickr.com/800/600/child,safety,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=sb1_vLijK40",
                    "https://www.youtube.com/watch?v=8CQldQfW_oY"
                ],
                "application_deadline": timezone.now() + timedelta(days=34),
                "start_date": timezone.now().date() + timedelta(days=46),
                "end_date": timezone.now().date() + timedelta(days=66),
                "is_featured": False,
            },
            {
                "title_en": "Tourism & Eco-Enterprise Development",
                "teaser_en": "Develop community-based tourism and eco-enterprises.",
                "background_objectives_en": "Tourism creates income; we develop enterprises and provide training.",
                "tasks_eligibility_en": "Tasks: Enterprise training, marketing. Eligibility: Business/tourism background.",
                "country_en": "Ecuador",
                "theme_en": "Economic Development",
                "title_zh_tw": "旅遊與生態企業發展",
                "teaser_zh_tw": "發展社區旅遊和生態企業。",
                "background_objectives_zh_tw": "旅遊創造收入；我們開發企業並提供培訓。",
                "tasks_eligibility_zh_tw": "任務：企業培訓、行銷。資格：商業或旅遊背景。",
                "country_zh_tw": "厄瓜多",
                "theme_zh_tw": "經濟發展",
                "kicc_project_id": "ECO-EC-028",
                "duration": 31,
                "difficulty": "Medium",
                "total_headcount": 20,
                "cover_image_url": "https://loremflickr.com/800/600/eco,tourism,enterprise",
                "image_urls": [
                    "https://loremflickr.com/800/600/tourism,enterprise,1",
                    "https://loremflickr.com/800/600/tourism,enterprise,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=lTMpt8kjbBQ",
                    "https://www.youtube.com/watch?v=m-QsbfsBjk0"
                ],
                "application_deadline": timezone.now() + timedelta(days=42),
                "start_date": timezone.now().date() + timedelta(days=56),
                "end_date": timezone.now().date() + timedelta(days=78),
                "is_featured": True,
            },
            {
                "title_en": "Gender Equality & Women's Rights",
                "teaser_en": "Promote gender equality and women's rights awareness.",
                "background_objectives_en": "Gender inequality persists; we teach rights and advocate for equality.",
                "tasks_eligibility_en": "Tasks: Training, advocacy. Eligibility: Gender studies/activism background.",
                "country_en": "Sierra Leone",
                "theme_en": "Gender & Empowerment",
                "title_zh_tw": "性別平等與婦女權利",
                "teaser_zh_tw": "推廣性別平等和婦女權利意識。",
                "background_objectives_zh_tw": "性別不平等持續存在；我們教授權利並倡導平等。",
                "tasks_eligibility_zh_tw": "任務：培訓、倡導。資格：性別研究或行動背景。",
                "country_zh_tw": "獅子山",
                "theme_zh_tw": "性別與賦權",
                "kicc_project_id": "GEN-SL-029",
                "duration": 25,
                "difficulty": "Easy",
                "total_headcount": 32,
                "cover_image_url": "https://loremflickr.com/800/600/gender,equality,women",
                "image_urls": [
                    "https://loremflickr.com/800/600/women,rights,1",
                    "https://loremflickr.com/800/600/women,rights,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=dIk6V68sBm8",
                    "https://www.youtube.com/watch?v=QKs8bqQ-0Ck"
                ],
                "application_deadline": timezone.now() + timedelta(days=28),
                "start_date": timezone.now().date() + timedelta(days=38),
                "end_date": timezone.now().date() + timedelta(days=55),
                "is_featured": False,
            },
            {
                "title_en": "Rural Technology Transfer",
                "teaser_en": "Transfer modern farming and production technologies to rural areas.",
                "background_objectives_en": "Technology gap limits productivity; we introduce modern methods.",
                "tasks_eligibility_en": "Tasks: Technology training, demonstration. Eligibility: Technical background.",
                "country_en": "Nigeria",
                "theme_en": "Agriculture & Technology",
                "title_zh_tw": "農村技術轉移",
                "teaser_zh_tw": "將現代農業和生產技術轉移到農村地區。",
                "background_objectives_zh_tw": "技術差距限制生產力；我們介紹現代方法。",
                "tasks_eligibility_zh_tw": "任務：技術培訓、示範。資格：技術背景。",
                "country_zh_tw": "奈及利亞",
                "theme_zh_tw": "農業與技術",
                "kicc_project_id": "AGR-NG-030",
                "duration": 36,
                "difficulty": "Medium",
                "total_headcount": 21,
                "cover_image_url": "https://loremflickr.com/800/600/rural,technology,agriculture",
                "image_urls": [
                    "https://loremflickr.com/800/600/rural,technology,1",
                    "https://loremflickr.com/800/600/rural,technology,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=KWaOjypn3Zo",
                    "https://www.youtube.com/watch?v=1pca674L1OA"
                ],
                "application_deadline": timezone.now() + timedelta(days=52),
                "start_date": timezone.now().date() + timedelta(days=66),
                "end_date": timezone.now().date() + timedelta(days=92),
                "is_featured": False,
            }
        ]

        for p_data in projects_data:
            if not Project.objects.filter(kicc_project_id=p_data['kicc_project_id']).exists():
                Project.objects.create(**p_data)
                self.stdout.write(self.style.SUCCESS(f"Created project: {p_data['title_en']}"))
            else:
                self.stdout.write(f"Project {p_data['kicc_project_id']} already exists.")