from django.core.management.base import BaseCommand
from django.utils import timezone
from django.db import connection
from apps.users.models import CustomUser
from datetime import datetime, timedelta
import random

class Command(BaseCommand):
    help = 'Seeds the database with test users for volunteer platform'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear all existing users before seeding',
        )

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding Users...')

        if kwargs.get('clear'):
            CustomUser.objects.all().delete()
            self.stdout.write(self.style.SUCCESS('Cleared all existing users'))
            
            # Reset auto-increment ID
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM sqlite_sequence WHERE name='users_customuser'")

        # List of realistic user data (40+ users)
        users_data = [
            {
                "username": "sarah_chen",
                "first_name": "Sarah",
                "last_name": "Chen",
                "email": "sarah.chen@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1995, 3, 15).date(),
                "gender": "Female",
                "blood_group": "A+",
                "address": "456 Green Street, Taipei, Taiwan",
                "contact": "+886912345678",
                "country_code": "TW",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "david_kim",
                "first_name": "David",
                "last_name": "Kim",
                "email": "david.kim@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1992, 7, 22).date(),
                "gender": "Male",
                "blood_group": "O+",
                "address": "123 Volunteer Lane, Seoul, South Korea",
                "contact": "+82109876543",
                "country_code": "KR",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "maria_santos",
                "first_name": "Maria",
                "last_name": "Santos",
                "email": "maria.santos@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1998, 11, 8).date(),
                "gender": "Female",
                "blood_group": "B+",
                "address": "789 Community Road, Manila, Philippines",
                "contact": "+63917234567",
                "country_code": "PH",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "james_wilson",
                "first_name": "James",
                "last_name": "Wilson",
                "email": "james.wilson@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1990, 5, 10).date(),
                "gender": "Male",
                "blood_group": "A-",
                "address": "321 Charity Avenue, London, UK",
                "contact": "+441234567890",
                "country_code": "GB",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "priya_patel",
                "first_name": "Priya",
                "last_name": "Patel",
                "email": "priya.patel@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1996, 2, 28).date(),
                "gender": "Female",
                "blood_group": "B-",
                "address": "654 Hope Street, Mumbai, India",
                "contact": "+919876543210",
                "country_code": "IN",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "alex_moreno",
                "first_name": "Alex",
                "last_name": "Moreno",
                "email": "alex.moreno@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1993, 9, 17).date(),
                "gender": "Other",
                "blood_group": "AB+",
                "address": "987 Progress Lane, Buenos Aires, Argentina",
                "contact": "+541145678901",
                "country_code": "AR",
                "login_method": "github",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "emma_white",
                "first_name": "Emma",
                "last_name": "White",
                "email": "emma.white@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1997, 6, 3).date(),
                "gender": "Female",
                "blood_group": "O-",
                "address": "111 Service Road, Sydney, Australia",
                "contact": "+61212345678",
                "country_code": "AU",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "mustafa_ahmed",
                "first_name": "Mustafa",
                "last_name": "Ahmed",
                "email": "mustafa.ahmed@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1991, 12, 25).date(),
                "gender": "Male",
                "blood_group": "AB-",
                "address": "222 Peace Avenue, Cairo, Egypt",
                "contact": "+201012345678",
                "country_code": "EG",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "yuki_tanaka",
                "first_name": "Yuki",
                "last_name": "Tanaka",
                "email": "yuki.tanaka@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1994, 8, 12).date(),
                "gender": "Female",
                "blood_group": "A+",
                "address": "333 Hope Lane, Tokyo, Japan",
                "contact": "+81312345678",
                "country_code": "JP",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "carlos_rodriguez",
                "first_name": "Carlos",
                "last_name": "Rodriguez",
                "email": "carlos.rodriguez@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1989, 1, 19).date(),
                "gender": "Male",
                "blood_group": "O+",
                "address": "444 Solidarity Street, Mexico City, Mexico",
                "contact": "+525512345678",
                "country_code": "MX",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "nina_petrov",
                "first_name": "Nina",
                "last_name": "Petrov",
                "email": "nina.petrov@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1999, 4, 7).date(),
                "gender": "Female",
                "blood_group": "B+",
                "address": "555 Unity Road, Moscow, Russia",
                "contact": "+79012345678",
                "country_code": "RU",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "liam_oconnor",
                "first_name": "Liam",
                "last_name": "O'Connor",
                "email": "liam.oconnor@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1992, 10, 30).date(),
                "gender": "Male",
                "blood_group": "A-",
                "address": "666 Celtic Way, Dublin, Ireland",
                "contact": "+35312345678",
                "country_code": "IE",
                "login_method": "github",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "sophia_diaz",
                "first_name": "Sophia",
                "last_name": "Diaz",
                "email": "sophia.diaz@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1995, 7, 14).date(),
                "gender": "Female",
                "blood_group": "AB+",
                "address": "777 Esperanza Lane, Madrid, Spain",
                "contact": "+34912345678",
                "country_code": "ES",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "lucas_costa",
                "first_name": "Lucas",
                "last_name": "Costa",
                "email": "lucas.costa@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1993, 3, 21).date(),
                "gender": "Male",
                "blood_group": "O-",
                "address": "888 Felicidade Road, São Paulo, Brazil",
                "contact": "+551112345678",
                "country_code": "BR",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "aisha_malik",
                "first_name": "Aisha",
                "last_name": "Malik",
                "email": "aisha.malik@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1996, 9, 5).date(),
                "gender": "Female",
                "blood_group": "B-",
                "address": "999 Peace Street, Karachi, Pakistan",
                "contact": "+923012345678",
                "country_code": "PK",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "oliver_mueller",
                "first_name": "Oliver",
                "last_name": "Mueller",
                "email": "oliver.mueller@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1991, 6, 11).date(),
                "gender": "Male",
                "blood_group": "A+",
                "address": "111 Hoffnung Street, Berlin, Germany",
                "contact": "+493012345678",
                "country_code": "DE",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "chloe_martin",
                "first_name": "Chloe",
                "last_name": "Martin",
                "email": "chloe.martin@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1997, 11, 23).date(),
                "gender": "Female",
                "blood_group": "AB-",
                "address": "222 Joie Road, Paris, France",
                "contact": "+33112345678",
                "country_code": "FR",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "antonio_gomes",
                "first_name": "Antonio",
                "last_name": "Gomes",
                "email": "antonio.gomes@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1988, 2, 8).date(),
                "gender": "Male",
                "blood_group": "O+",
                "address": "333 Esperança Lane, Lisbon, Portugal",
                "contact": "+351912345678",
                "country_code": "PT",
                "login_method": "github",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "isabella_rossi",
                "first_name": "Isabella",
                "last_name": "Rossi",
                "email": "isabella.rossi@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1994, 5, 19).date(),
                "gender": "Female",
                "blood_group": "B+",
                "address": "444 Speranza Street, Rome, Italy",
                "contact": "+393912345678",
                "country_code": "IT",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "marcus_johnson",
                "first_name": "Marcus",
                "last_name": "Johnson",
                "email": "marcus.johnson@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1990, 8, 27).date(),
                "gender": "Male",
                "blood_group": "A-",
                "address": "555 Freedom Lane, New York, USA",
                "contact": "+12125551234",
                "country_code": "US",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "lily_thompson",
                "first_name": "Lily",
                "last_name": "Thompson",
                "email": "lily.thompson@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1998, 12, 2).date(),
                "gender": "Female",
                "blood_group": "AB+",
                "address": "666 Maple Avenue, Vancouver, Canada",
                "contact": "+16042345678",
                "country_code": "CA",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "ming_zhang",
                "first_name": "Ming",
                "last_name": "Zhang",
                "email": "ming.zhang@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1993, 4, 16).date(),
                "gender": "Male",
                "blood_group": "O-",
                "address": "777 Peace Road, Beijing, China",
                "contact": "+861012345678",
                "country_code": "CN",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "ngozi_adeyemi",
                "first_name": "Ngozi",
                "last_name": "Adeyemi",
                "email": "ngozi.adeyemi@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1995, 7, 9).date(),
                "gender": "Female",
                "blood_group": "B-",
                "address": "888 Unity Street, Lagos, Nigeria",
                "contact": "+2341012345678",
                "country_code": "NG",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "ravi_kapoor",
                "first_name": "Ravi",
                "last_name": "Kapoor",
                "email": "ravi.kapoor@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1991, 10, 13).date(),
                "gender": "Male",
                "blood_group": "A+",
                "address": "999 Asha Lane, Delhi, India",
                "contact": "+919876543210",
                "country_code": "IN",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "fatima_hassan",
                "first_name": "Fatima",
                "last_name": "Hassan",
                "email": "fatima.hassan@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1997, 1, 6).date(),
                "gender": "Female",
                "blood_group": "AB-",
                "address": "111 Noor Street, Nairobi, Kenya",
                "contact": "+254712345678",
                "country_code": "KE",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "bangkok_volunteer",
                "first_name": "Somchai",
                "last_name": "Pongkham",
                "email": "somchai.pongkham@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1994, 3, 28).date(),
                "gender": "Male",
                "blood_group": "O+",
                "address": "222 Service Road, Bangkok, Thailand",
                "contact": "+66812345678",
                "country_code": "TH",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "hannah_berg",
                "first_name": "Hannah",
                "last_name": "Berg",
                "email": "hannah.berg@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1999, 9, 14).date(),
                "gender": "Female",
                "blood_group": "B+",
                "address": "333 Hjerte Lane, Copenhagen, Denmark",
                "contact": "+4512345678",
                "country_code": "DK",
                "login_method": "github",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "jean_dubois",
                "first_name": "Jean",
                "last_name": "Dubois",
                "email": "jean.dubois@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1989, 11, 20).date(),
                "gender": "Male",
                "blood_group": "A-",
                "address": "444 Solidarité Avenue, Geneva, Switzerland",
                "contact": "+41912345678",
                "country_code": "CH",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "jessica_nguyen",
                "first_name": "Jessica",
                "last_name": "Nguyen",
                "email": "jessica.nguyen@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1996, 6, 22).date(),
                "gender": "Female",
                "blood_group": "AB+",
                "address": "555 Hope Road, Hanoi, Vietnam",
                "contact": "+84912345678",
                "country_code": "VN",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "nicholas_larson",
                "first_name": "Nicholas",
                "last_name": "Larson",
                "email": "nicholas.larson@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1992, 2, 5).date(),
                "gender": "Male",
                "blood_group": "O-",
                "address": "666 Service Lane, Stockholm, Sweden",
                "contact": "+46812345678",
                "country_code": "SE",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "amara_diop",
                "first_name": "Amara",
                "last_name": "Diop",
                "email": "amara.diop@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1998, 8, 11).date(),
                "gender": "Female",
                "blood_group": "B-",
                "address": "777 Ubuntu Lane, Dakar, Senegal",
                "contact": "+221912345678",
                "country_code": "SN",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "rafael_santos",
                "first_name": "Rafael",
                "last_name": "Santos",
                "email": "rafael.santos@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1990, 5, 17).date(),
                "gender": "Male",
                "blood_group": "A+",
                "address": "888 Caridad Street, Lima, Peru",
                "contact": "+51912345678",
                "country_code": "PE",
                "login_method": "github",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "elena_kowalski",
                "first_name": "Elena",
                "last_name": "Kowalski",
                "email": "elena.kowalski@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1994, 9, 25).date(),
                "gender": "Female",
                "blood_group": "AB-",
                "address": "999 Solidarność Lane, Warsaw, Poland",
                "contact": "+48512345678",
                "country_code": "PL",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "tom_anderson",
                "first_name": "Tom",
                "last_name": "Anderson",
                "email": "tom.anderson@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1987, 7, 3).date(),
                "gender": "Male",
                "blood_group": "O+",
                "address": "111 Hope Street, Auckland, New Zealand",
                "contact": "+64212345678",
                "country_code": "NZ",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "diana_cruz",
                "first_name": "Diana",
                "last_name": "Cruz",
                "email": "diana.cruz@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1997, 4, 29).date(),
                "gender": "Female",
                "blood_group": "B+",
                "address": "222 Esperanza Avenue, Bogotá, Colombia",
                "contact": "+571912345678",
                "country_code": "CO",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "marco_volkov",
                "first_name": "Marco",
                "last_name": "Volkov",
                "email": "marco.volkov@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1993, 12, 8).date(),
                "gender": "Male",
                "blood_group": "A-",
                "address": "333 Мир Road, Saint Petersburg, Russia",
                "contact": "+79112345678",
                "country_code": "RU",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "yasmin_ghani",
                "first_name": "Yasmin",
                "last_name": "Ghani",
                "email": "yasmin.ghani@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1996, 3, 14).date(),
                "gender": "Female",
                "blood_group": "AB+",
                "address": "444 Salam Lane, Dubai, UAE",
                "contact": "+971912345678",
                "country_code": "AE",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "leo_magnusson",
                "first_name": "Leo",
                "last_name": "Magnusson",
                "email": "leo.magnusson@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1991, 8, 19).date(),
                "gender": "Male",
                "blood_group": "O-",
                "address": "555 Framtid Road, Reykjavik, Iceland",
                "contact": "+3541234567",
                "country_code": "IS",
                "login_method": "github",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "gloria_torres",
                "first_name": "Gloria",
                "last_name": "Torres",
                "email": "gloria.torres@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1995, 10, 7).date(),
                "gender": "Female",
                "blood_group": "B-",
                "address": "666 Paz Lane, Santiago, Chile",
                "contact": "+562912345678",
                "country_code": "CL",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "vincenzo_rossi",
                "first_name": "Vincenzo",
                "last_name": "Rossi",
                "email": "vincenzo.rossi@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1989, 1, 12).date(),
                "gender": "Male",
                "blood_group": "A+",
                "address": "777 Amore Lane, Venice, Italy",
                "contact": "+39412345678",
                "country_code": "IT",
                "login_method": "google",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "samira_khan",
                "first_name": "Samira",
                "last_name": "Khan",
                "email": "samira.khan@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1998, 6, 30).date(),
                "gender": "Female",
                "blood_group": "AB-",
                "address": "888 Shanti Lane, Dhaka, Bangladesh",
                "contact": "+88012345678",
                "country_code": "BD",
                "login_method": "facebook",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
            {
                "username": "oscar_williams",
                "first_name": "Oscar",
                "last_name": "Williams",
                "email": "oscar.williams@email.com",
                "password": "SecurePass123!",
                "date_of_birth": datetime(1992, 11, 21).date(),
                "gender": "Male",
                "blood_group": "O+",
                "address": "999 Justice Lane, Los Angeles, USA",
                "contact": "+13105551234",
                "country_code": "US",
                "login_method": "email",
                "is_active": True,
                "onboarding_complete": True,
                "email_verified": True,
            },
        ]

        # Create users
        for u_data in users_data:
            password = u_data.pop("password")
            
            # Check if user already exists
            if not CustomUser.objects.filter(username=u_data['username']).exists():
                user = CustomUser.objects.create_user(**u_data, password=password)
                self.stdout.write(self.style.SUCCESS(f"Created user: {user.get_full_name()} ({user.username})"))
            else:
                self.stdout.write(f"User '{u_data['username']}' already exists.")

        self.stdout.write(self.style.SUCCESS("User seeding completed successfully!"))
