from django.core.management.base import BaseCommand
from django.utils import timezone
from apps.content.models import SuccessStory, Project
import random

class Command(BaseCommand):
    help = 'Seeds the database with Success Stories (EN & ZH-TW)'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding Success Stories...')

        # Try to fetch a project to link to
        projects = Project.objects.all()
        related_proj = projects.first() if projects.exists() else None

        stories_data = [
            {
                # English
                "title_en": "Sarah's Month Teaching in Hanoi",
                "body_en": "Living in Hanoi was a life-changing experience. The students were eager to learn, and despite the language barrier, we connected through games and laughter.",
                # Traditional Chinese
                "title_zh_tw": "莎拉在河內教書的一個月",
                "body_zh_tw": "在河內生活是一次改變人生的經歷。學生們渴望學習，儘管有語言障礙，我們通過遊戲和歡笑建立了聯繫。",

                "beneficiaries": 120,
                "total_hours_contributed": 160,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": True,
                
                # Images via Lorem Flickr (20+ images)
                "cover_image_url": "https://loremflickr.com/800/600/hanoi,vietnam,girl",
                "image_urls": [
                    "https://loremflickr.com/800/600/teaching,students,1",
                    "https://loremflickr.com/800/600/teaching,students,2",
                    "https://loremflickr.com/800/600/classroom,1",
                    "https://loremflickr.com/800/600/classroom,2",
                    "https://loremflickr.com/800/600/teacher,1",
                    "https://loremflickr.com/800/600/teacher,2",
                    "https://loremflickr.com/800/600/learning,1",
                    "https://loremflickr.com/800/600/learning,2",
                    "https://loremflickr.com/800/600/games,education,1",
                    "https://loremflickr.com/800/600/games,education,2",
                    "https://loremflickr.com/800/600/smiling,children,1",
                    "https://loremflickr.com/800/600/smiling,children,2",
                    "https://loremflickr.com/800/600/school,playground,1",
                    "https://loremflickr.com/800/600/school,playground,2",
                    "https://loremflickr.com/800/600/storytelling,1",
                    "https://loremflickr.com/800/600/storytelling,2",
                    "https://loremflickr.com/800/600/volunteer,work,1",
                    "https://loremflickr.com/800/600/volunteer,work,2",
                    "https://loremflickr.com/800/600/community,event,1",
                    "https://loremflickr.com/800/600/community,event,2",
                    "https://loremflickr.com/800/600/hanoi,street,1",
                    "https://loremflickr.com/800/600/hanoi,street,2",
                    "https://loremflickr.com/800/600/student,achievement,1",
                    "https://loremflickr.com/800/600/student,achievement,2",
                ],
                
                # Video from Kingslish Channel
                "video_urls": [
                    "https://www.youtube.com/@kingslishapp"
                ],
            },
            {
                # English
                "title_en": "Restoring the Coral Reefs",
                "body_en": "Diving down to plant new coral fragments was hard work, but seeing the fish return to the reef made every minute worth it.",
                # Traditional Chinese
                "title_zh_tw": "修復珊瑚礁",
                "body_zh_tw": "潛入水中種植新的珊瑚碎片是一項艱苦的工作，但看到魚群回到珊瑚礁，每一分鐘都值得。",

                "beneficiaries": 0,
                "total_hours_contributed": 50,
                "published_at": timezone.now(),
                "related_project": None,
                "is_hero_highlight": True,
                
                # Images via Lorem Flickr (20+ images)
                "cover_image_url": "https://loremflickr.com/800/600/coral,reef,diving",
                "image_urls": [
                    "https://loremflickr.com/800/600/coral,reef,1",
                    "https://loremflickr.com/800/600/coral,reef,2",
                    "https://loremflickr.com/800/600/diver,1",
                    "https://loremflickr.com/800/600/diver,2",
                    "https://loremflickr.com/800/600/underwater,1",
                    "https://loremflickr.com/800/600/underwater,2",
                    "https://loremflickr.com/800/600/fish,1",
                    "https://loremflickr.com/800/600/fish,2",
                    "https://loremflickr.com/800/600/frag,planting,1",
                    "https://loremflickr.com/800/600/frag,planting,2",
                    "https://loremflickr.com/800/600/research,1",
                    "https://loremflickr.com/800/600/research,2",
                    "https://loremflickr.com/800/600/boat,work,1",
                    "https://loremflickr.com/800/600/boat,work,2",
                    "https://loremflickr.com/800/600/community,volunteers,1",
                    "https://loremflickr.com/800/600/community,volunteers,2",
                    "https://loremflickr.com/800/600/beach,cleanup,1",
                    "https://loremflickr.com/800/600/beach,cleanup,2",
                    "https://loremflickr.com/800/600/sea,turtle,1",
                    "https://loremflickr.com/800/600/sea,turtle,2",
                    "https://loremflickr.com/800/600/monitoring,1",
                    "https://loremflickr.com/800/600/monitoring,2",
                    "https://loremflickr.com/800/600/ecology,1",
                    "https://loremflickr.com/800/600/ecology,2",
                ],
                
                # Video from Kingslish Channel
                "video_urls": [
                    "https://www.youtube.com/@kingslishapp"
                ],
            }
        ]

        # Add additional success stories
        stories_data += [
            {
                "title_en": "Solar Village: A Day with Volunteers",
                "body_en": "The day started at 6 AM as our team carried solar panels into the fields; by afternoon, lights were bringing smiles to families who had been in the dark for years.",
                "title_zh_tw": "太陽能村落：與志工的一天",
                "body_zh_tw": "一天從清晨開始，我們的團隊把太陽能板搬到田間；午後，燈光為多年處於黑暗的家庭帶來笑容。",
                "beneficiaries": 45,
                "total_hours_contributed": 200,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/solar,village,volunteers",
                "image_urls": [
                    "https://loremflickr.com/800/600/solar,install,1",
                    "https://loremflickr.com/800/600/solar,install,2",
                    "https://loremflickr.com/800/600/panel,team,1",
                    "https://loremflickr.com/800/600/panel,team,2",
                    "https://loremflickr.com/800/600/night,light,1",
                    "https://loremflickr.com/800/600/night,light,2",
                    "https://loremflickr.com/800/600/solar,education,1",
                    "https://loremflickr.com/800/600/solar,education,2",
                    "https://loremflickr.com/800/600/maintenance,1",
                    "https://loremflickr.com/800/600/maintenance,2",
                    "https://loremflickr.com/800/600/community,meeting,1",
                    "https://loremflickr.com/800/600/community,meeting,2",
                    "https://loremflickr.com/800/600/children,study,1",
                    "https://loremflickr.com/800/600/children,study,2",
                    "https://loremflickr.com/800/600/engineer,teaching,1",
                    "https://loremflickr.com/800/600/engineer,teaching,2",
                    "https://loremflickr.com/800/600/tools,work,1",
                    "https://loremflickr.com/800/600/tools,work,2",
                    "https://loremflickr.com/800/600/family,happy,1",
                    "https://loremflickr.com/800/600/family,happy,2",
                    "https://loremflickr.com/800/600/remote,village,1",
                    "https://loremflickr.com/800/600/remote,village,2",
                    "https://loremflickr.com/800/600/solar,infrastructure,1",
                    "https://loremflickr.com/800/600/solar,infrastructure,2",
                ],
                "video_urls": ["https://www.youtube.com/watch?v=solar_village_story"],
            },
            {
                "title_en": "Women Entrepreneurs Transforming Their Community",
                "body_en": "Small loans, new skills, and mentorship helped dozens of women launch their microbusinesses — now they provide consistent income to their families.",
                "title_zh_tw": "婦女創業家改變社區",
                "body_zh_tw": "小額貸款、新技能和指導幫助數十名婦女創立微型企業，現在她們為家庭提供穩定收入。",
                "beneficiaries": 200,
                "total_hours_contributed": 300,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": False,
                "cover_image_url": "https://loremflickr.com/800/600/women,entrepreneur,workshop",
                "image_urls": [
                    "https://loremflickr.com/800/600/women,entrepreneur,1",
                    "https://loremflickr.com/800/600/women,entrepreneur,2",
                    "https://loremflickr.com/800/600/product,display,1",
                    "https://loremflickr.com/800/600/product,display,2",
                    "https://loremflickr.com/800/600/training,1",
                    "https://loremflickr.com/800/600/training,2",
                    "https://loremflickr.com/800/600/mentorship,1",
                    "https://loremflickr.com/800/600/mentorship,2",
                    "https://loremflickr.com/800/600/sewing,1",
                    "https://loremflickr.com/800/600/sewing,2",
                    "https://loremflickr.com/800/600/market,stand,1",
                    "https://loremflickr.com/800/600/market,stand,2",
                    "https://loremflickr.com/800/600/customer,interaction,1",
                    "https://loremflickr.com/800/600/customer,interaction,2",
                    "https://loremflickr.com/800/600/business,planning,1",
                    "https://loremflickr.com/800/600/business,planning,2",
                    "https://loremflickr.com/800/600/bazaar,1",
                    "https://loremflickr.com/800/600/bazaar,2",
                    "https://loremflickr.com/800/600/networking,1",
                    "https://loremflickr.com/800/600/networking,2",
                    "https://loremflickr.com/800/600/loan,training,1",
                    "https://loremflickr.com/800/600/loan,training,2",
                    "https://loremflickr.com/800/600/community,celebration,1",
                    "https://loremflickr.com/800/600/community,celebration,2",
                ],
                "video_urls": ["https://www.youtube.com/watch?v=women_empowerment"],
            },
            {
                "title_en": "Community Garden Brings New Life to Flood-Prone Area",
                "body_en": "Through raised beds, permaculture techniques, and community seeds, households improved food access and diet diversity in their neighborhoods.",
                "title_zh_tw": "社區花園為易洪水地區帶來新生命",
                "body_zh_tw": "透過高床、永續農法與社區種子，家庭在鄰里中改善了食物取得與飲食多樣性。",
                "beneficiaries": 80,
                "total_hours_contributed": 100,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_hero_highlight": False,
                "cover_image_url": "https://loremflickr.com/800/600/community,garden,farm",
                "image_urls": [
                    "https://loremflickr.com/800/600/garden,raisedbed,1",
                    "https://loremflickr.com/800/600/garden,raisedbed,2",
                    "https://loremflickr.com/800/600/permaculture,1",
                    "https://loremflickr.com/800/600/permaculture,2",
                    "https://loremflickr.com/800/600/compost,1",
                    "https://loremflickr.com/800/600/compost,2",
                    "https://loremflickr.com/800/600/community,planting,1",
                    "https://loremflickr.com/800/600/community,planting,2",
                    "https://loremflickr.com/800/600/vegetables,harvest,1",
                    "https://loremflickr.com/800/600/vegetables,harvest,2",
                    "https://loremflickr.com/800/600/farmers,1",
                    "https://loremflickr.com/800/600/farmers,2",
                    "https://loremflickr.com/800/600/seeds,distribution,1",
                    "https://loremflickr.com/800/600/seeds,distribution,2",
                    "https://loremflickr.com/800/600/education,workshop,1",
                    "https://loremflickr.com/800/600/education,workshop,2",
                    "https://loremflickr.com/800/600/kids,garden,1",
                    "https://loremflickr.com/800/600/kids,garden,2",
                    "https://loremflickr.com/800/600/irrigation,setup,1",
                    "https://loremflickr.com/800/600/irrigation,setup,2",
                    "https://loremflickr.com/800/600/soil,improvement,1",
                    "https://loremflickr.com/800/600/soil,improvement,2",
                    "https://loremflickr.com/800/600/community,market,1",
                    "https://loremflickr.com/800/600/community,market,2",
                ],
                "video_urls": ["https://www.youtube.com/watch?v=community_garden_story"],
            },
            {
                "title_en": "Clean Water Changes Everything",
                "body_en": "Installing the first well in the village meant families no longer had to walk 5km daily for water. Children now attend school instead of fetching water.",
                "title_zh_tw": "乾淨水改變一切",
                "body_zh_tw": "在村莊安裝第一口井意味著家庭不再需要每天走5公里取水。孩子們現在上學而不是去取水。",
                "beneficiaries": 150,
                "total_hours_contributed": 250,
                "published_at": timezone.now(),
                "related_project": None,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/water,well,village",
                "image_urls": [
                    "https://loremflickr.com/800/600/water,well,1",
                    "https://loremflickr.com/800/600/water,well,2",
                    "https://loremflickr.com/800/600/well,construction,1",
                    "https://loremflickr.com/800/600/well,construction,2",
                    "https://loremflickr.com/800/600/water,collection,1",
                    "https://loremflickr.com/800/600/water,collection,2",
                    "https://loremflickr.com/800/600/children,school,1",
                    "https://loremflickr.com/800/600/children,school,2",
                    "https://loremflickr.com/800/600/village,community,1",
                    "https://loremflickr.com/800/600/village,community,2",
                    "https://loremflickr.com/800/600/water,pump,1",
                    "https://loremflickr.com/800/600/water,pump,2",
                    "https://loremflickr.com/800/600/health,education,1",
                    "https://loremflickr.com/800/600/health,education,2",
                    "https://loremflickr.com/800/600/sanitation,1",
                    "https://loremflickr.com/800/600/sanitation,2",
                    "https://loremflickr.com/800/600/women,water,1",
                    "https://loremflickr.com/800/600/women,water,2",
                    "https://loremflickr.com/800/600/celebration,opening,1",
                    "https://loremflickr.com/800/600/celebration,opening,2",
                    "https://loremflickr.com/800/600/testing,water,1",
                    "https://loremflickr.com/800/600/testing,water,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=Cr7Se5revOk",
                    "https://www.youtube.com/watch?v=5U9DLtSwNgQ",
                    "https://www.youtube.com/watch?v=0x5N_7d82JY",
                    "https://www.youtube.com/watch?v=LYowTbsj8Zs",
                    "https://www.youtube.com/watch?v=BU1TQY-SfkA"
                ],
            },
            {
                "title_en": "From Dropout to Entrepreneur",
                "body_en": "Maria left school at 12, but our skills program changed her life. Now she runs her own tailoring business and has trained 5 others.",
                "title_zh_tw": "從輟學生到企業家",
                "body_zh_tw": "瑪麗亞12歲就輟學，但我們的技能計畫改變了她的人生。現在她經營自己的裁縫業務，並訓練了5個人。",
                "beneficiaries": 30,
                "total_hours_contributed": 180,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/tailoring,entrepreneur,woman",
                "image_urls": [
                    "https://loremflickr.com/800/600/tailoring,skills,1",
                    "https://loremflickr.com/800/600/tailoring,skills,2",
                    "https://loremflickr.com/800/600/sewing,machine,1",
                    "https://loremflickr.com/800/600/sewing,machine,2",
                    "https://loremflickr.com/800/600/fabric,materials,1",
                    "https://loremflickr.com/800/600/fabric,materials,2",
                    "https://loremflickr.com/800/600/training,students,1",
                    "https://loremflickr.com/800/600/training,students,2",
                    "https://loremflickr.com/800/600/workshop,space,1",
                    "https://loremflickr.com/800/600/workshop,space,2",
                    "https://loremflickr.com/800/600/finished,products,1",
                    "https://loremflickr.com/800/600/finished,products,2",
                    "https://loremflickr.com/800/600/market,shop,1",
                    "https://loremflickr.com/800/600/market,shop,2",
                    "https://loremflickr.com/800/600/customer,happy,1",
                    "https://loremflickr.com/800/600/customer,happy,2",
                    "https://loremflickr.com/800/600/entrepreneur,proud,1",
                    "https://loremflickr.com/800/600/entrepreneur,proud,2",
                    "https://loremflickr.com/800/600/business,growth,1",
                    "https://loremflickr.com/800/600/business,growth,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=2---xb-BmBw",
                    "https://www.youtube.com/watch?v=KaWQ2Ua9CW8",
                    "https://www.youtube.com/watch?v=tYANvrEzvKk",
                    "https://www.youtube.com/watch?v=xJl9i6nsmvw",
                    "https://www.youtube.com/watch?v=B0iwi5EXFWU"
                ],
            },
            {
                "title_en": "Forest Recovery Through Community Action",
                "body_en": "Planting 10,000 trees seemed impossible, but the village did it together. Now wildlife is returning and soil quality has improved dramatically.",
                "title_zh_tw": "透過社區行動恢復森林",
                "body_zh_tw": "種植10,000棵樹似乎不可能，但村莊一起完成了。現在野生動物正在回歸，土壤質量有了顯著改善。",
                "beneficiaries": 200,
                "total_hours_contributed": 400,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": False,
                "cover_image_url": "https://loremflickr.com/800/600/forest,reforestation,trees",
                "image_urls": [
                    "https://loremflickr.com/800/600/tree,planting,1",
                    "https://loremflickr.com/800/600/tree,planting,2",
                    "https://loremflickr.com/800/600/seedling,nursery,1",
                    "https://loremflickr.com/800/600/seedling,nursery,2",
                    "https://loremflickr.com/800/600/volunteers,forest,1",
                    "https://loremflickr.com/800/600/volunteers,forest,2",
                    "https://loremflickr.com/800/600/soil,preparation,1",
                    "https://loremflickr.com/800/600/soil,preparation,2",
                    "https://loremflickr.com/800/600/children,planting,1",
                    "https://loremflickr.com/800/600/children,planting,2",
                    "https://loremflickr.com/800/600/forest,growth,1",
                    "https://loremflickr.com/800/600/forest,growth,2",
                    "https://loremflickr.com/800/600/wildlife,return,1",
                    "https://loremflickr.com/800/600/wildlife,return,2",
                    "https://loremflickr.com/800/600/bird,monitoring,1",
                    "https://loremflickr.com/800/600/bird,monitoring,2",
                    "https://loremflickr.com/800/600/community,event,1",
                    "https://loremflickr.com/800/600/community,event,2",
                    "https://loremflickr.com/800/600/landscape,recovery,1",
                    "https://loremflickr.com/800/600/landscape,recovery,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=us7SMS44FIw",
                    "https://www.youtube.com/watch?v=w1EXAdzDAxA",
                    "https://www.youtube.com/watch?v=DSBcBSdJDaE",
                    "https://www.youtube.com/watch?v=PhJnZnQuuT0",
                    "https://www.youtube.com/watch?v=ywVS21j7fE8"
                ],
            },
            {
                "title_en": "Clinic Saves Lives in Remote Area",
                "body_en": "What started as a small health post is now delivering maternal care, vaccinations, and disease screening to 5,000+ people annually.",
                "title_zh_tw": "診所在偏遠地區拯救生命",
                "body_zh_tw": "從一個小衛生站開始，現在每年為5,000多人提供孕產婦保健、疫苗接種和疾病篩檢。",
                "beneficiaries": 5000,
                "total_hours_contributed": 800,
                "published_at": timezone.now(),
                "related_project": None,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/clinic,health,remote",
                "image_urls": [
                    "https://loremflickr.com/800/600/clinic,building,1",
                    "https://loremflickr.com/800/600/clinic,building,2",
                    "https://loremflickr.com/800/600/health,staff,1",
                    "https://loremflickr.com/800/600/health,staff,2",
                    "https://loremflickr.com/800/600/vaccination,1",
                    "https://loremflickr.com/800/600/vaccination,2",
                    "https://loremflickr.com/800/600/mother,child,1",
                    "https://loremflickr.com/800/600/mother,child,2",
                    "https://loremflickr.com/800/600/checkup,1",
                    "https://loremflickr.com/800/600/checkup,2",
                    "https://loremflickr.com/800/600/screening,1",
                    "https://loremflickr.com/800/600/screening,2",
                    "https://loremflickr.com/800/600/medicine,supplies,1",
                    "https://loremflickr.com/800/600/medicine,supplies,2",
                    "https://loremflickr.com/800/600/waiting,area,1",
                    "https://loremflickr.com/800/600/waiting,area,2",
                    "https://loremflickr.com/800/600/patient,care,1",
                    "https://loremflickr.com/800/600/patient,care,2",
                    "https://loremflickr.com/800/600/health,education,1",
                    "https://loremflickr.com/800/600/health,education,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=R-FhDcKJFqw",
                    "https://www.youtube.com/watch?v=7wDTkAiaNyc",
                    "https://www.youtube.com/watch?v=4l4UWZGxvoc",
                    "https://www.youtube.com/watch?v=DRIx1pXj0ag",
                    "https://www.youtube.com/watch?v=DFbb4dSzXRk"
                ],
            },
            {
                "title_en": "Street Children Find Hope in Education",
                "body_en": "Our education program brings 200+ street children off the streets and into classrooms. 80% have been reunited with families.",
                "title_zh_tw": "街頭兒童在教育中找到希望",
                "body_zh_tw": "我們的教育計畫將200多名街頭兒童從街上帶到教室。80%的兒童已與家人重聚。",
                "beneficiaries": 200,
                "total_hours_contributed": 600,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/children,education,hope",
                "image_urls": [
                    "https://loremflickr.com/800/600/children,classroom,1",
                    "https://loremflickr.com/800/600/children,classroom,2",
                    "https://loremflickr.com/800/600/education,program,1",
                    "https://loremflickr.com/800/600/education,program,2",
                    "https://loremflickr.com/800/600/books,learning,1",
                    "https://loremflickr.com/800/600/books,learning,2",
                    "https://loremflickr.com/800/600/tutor,support,1",
                    "https://loremflickr.com/800/600/tutor,support,2",
                    "https://loremflickr.com/800/600/shelter,safety,1",
                    "https://loremflickr.com/800/600/shelter,safety,2",
                    "https://loremflickr.com/800/600/meals,provided,1",
                    "https://loremflickr.com/800/600/meals,provided,2",
                    "https://loremflickr.com/800/600/counseling,1",
                    "https://loremflickr.com/800/600/counseling,2",
                    "https://loremflickr.com/800/600/family,reunion,1",
                    "https://loremflickr.com/800/600/family,reunion,2",
                    "https://loremflickr.com/800/600/graduation,1",
                    "https://loremflickr.com/800/600/graduation,2",
                    "https://loremflickr.com/800/600/future,bright,1",
                    "https://loremflickr.com/800/600/future,bright,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=shorts/3oZNHz3atqY",
                    "https://www.youtube.com/watch?v=shorts/DVCvwI46Sik",
                    "https://www.youtube.com/watch?v=iv6052eJ6I8",
                    "https://www.youtube.com/watch?v=a8DueDYaxvE",
                    "https://www.youtube.com/watch?v=o7O0Smy3jPo"
                ],
            },
            {
                "title_en": "Cooperative Coffee Farmers Increase Income 5x",
                "body_en": "By forming a cooperative and improving farming practices, 150 coffee farmers doubled their yields and tripled their market prices.",
                "title_zh_tw": "合作社咖啡農民收入增加5倍",
                "body_zh_tw": "透過成立合作社並改進耕作方法，150名咖啡農民將產量翻倍，市場價格增加三倍。",
                "beneficiaries": 150,
                "total_hours_contributed": 350,
                "published_at": timezone.now(),
                "related_project": None,
                "is_featured": False,
                "cover_image_url": "https://loremflickr.com/800/600/coffee,farmers,cooperative",
                "image_urls": [
                    "https://loremflickr.com/800/600/coffee,farm,1",
                    "https://loremflickr.com/800/600/coffee,farm,2",
                    "https://loremflickr.com/800/600/harvesting,coffee,1",
                    "https://loremflickr.com/800/600/harvesting,coffee,2",
                    "https://loremflickr.com/800/600/processing,beans,1",
                    "https://loremflickr.com/800/600/processing,beans,2",
                    "https://loremflickr.com/800/600/farmer,training,1",
                    "https://loremflickr.com/800/600/farmer,training,2",
                    "https://loremflickr.com/800/600/quality,control,1",
                    "https://loremflickr.com/800/600/quality,control,2",
                    "https://loremflickr.com/800/600/market,sale,1",
                    "https://loremflickr.com/800/600/market,sale,2",
                    "https://loremflickr.com/800/600/cooperative,meeting,1",
                    "https://loremflickr.com/800/600/cooperative,meeting,2",
                    "https://loremflickr.com/800/600/income,success,1",
                    "https://loremflickr.com/800/600/income,success,2",
                    "https://loremflickr.com/800/600/farm,expansion,1",
                    "https://loremflickr.com/800/600/farm,expansion,2",
                    "https://loremflickr.com/800/600/equipment,investment,1",
                    "https://loremflickr.com/800/600/equipment,investment,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=PzrEoE8AU3c",
                    "https://www.youtube.com/watch?v=_s9JzPWDcIc",
                    "https://www.youtube.com/watch?v=i-lrDYV_piE",
                    "https://www.youtube.com/watch?v=xaaiy2KcLkQ",
                    "https://www.youtube.com/watch?v=4ORYxFFs_oU"
                ],
            },
            {
                "title_en": "Girls Reclaim Their Education",
                "body_en": "250 girls in an education-restricted area are now in school. Our program fought against child marriage and created safe spaces for learning.",
                "title_zh_tw": "女孩重獲教育機會",
                "body_zh_tw": "在教育受限地區的250名女孩現在上學了。我們的計畫對抗兒童婚姻並為學習創造了安全的空間。",
                "beneficiaries": 250,
                "total_hours_contributed": 500,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/girls,education,school",
                "image_urls": [
                    "https://loremflickr.com/800/600/girls,classroom,1",
                    "https://loremflickr.com/800/600/girls,classroom,2",
                    "https://loremflickr.com/800/600/studying,together,1",
                    "https://loremflickr.com/800/600/studying,together,2",
                    "https://loremflickr.com/800/600/school,building,1",
                    "https://loremflickr.com/800/600/school,building,2",
                    "https://loremflickr.com/800/600/teacher,support,1",
                    "https://loremflickr.com/800/600/teacher,support,2",
                    "https://loremflickr.com/800/600/library,access,1",
                    "https://loremflickr.com/800/600/library,access,2",
                    "https://loremflickr.com/800/600/mentorship,1",
                    "https://loremflickr.com/800/600/mentorship,2",
                    "https://loremflickr.com/800/600/safe,space,1",
                    "https://loremflickr.com/800/600/safe,space,2",
                    "https://loremflickr.com/800/600/counseling,support,1",
                    "https://loremflickr.com/800/600/counseling,support,2",
                    "https://loremflickr.com/800/600/graduation,achievement,1",
                    "https://loremflickr.com/800/600/graduation,achievement,2",
                    "https://loremflickr.com/800/600/empowerment,1",
                    "https://loremflickr.com/800/600/empowerment,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=RbgBNE_G5pE",
                    "https://www.youtube.com/watch?v=AZfHFDJuVak",
                    "https://www.youtube.com/watch?v=ZRQYJucDSXM",
                    "https://www.youtube.com/watch?v=H-aBNHNB_6Y",
                    "https://www.youtube.com/watch?v=uOwNq-Nm-NU"
                ],
            },
            {
                "title_en": "Disaster-Resilient Community Survives Typhoon",
                "body_en": "After training in disaster preparedness, the community withstood a Category 4 typhoon with minimal casualties and rapid recovery.",
                "title_zh_tw": "災害復原力社區度過颱風",
                "body_zh_tw": "經過防災培訓後，社區經受了四級颱風，傷亡最少且迅速恢復。",
                "beneficiaries": 1000,
                "total_hours_contributed": 400,
                "published_at": timezone.now(),
                "related_project": None,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/disaster,preparedness,resilience",
                "image_urls": [
                    "https://loremflickr.com/800/600/disaster,training,1",
                    "https://loremflickr.com/800/600/disaster,training,2",
                    "https://loremflickr.com/800/600/evacuation,drill,1",
                    "https://loremflickr.com/800/600/evacuation,drill,2",
                    "https://loremflickr.com/800/600/shelter,setup,1",
                    "https://loremflickr.com/800/600/shelter,setup,2",
                    "https://loremflickr.com/800/600/supply,storage,1",
                    "https://loremflickr.com/800/600/supply,storage,2",
                    "https://loremflickr.com/800/600/community,prepared,1",
                    "https://loremflickr.com/800/600/community,prepared,2",
                    "https://loremflickr.com/800/600/recovery,effort,1",
                    "https://loremflickr.com/800/600/recovery,effort,2",
                    "https://loremflickr.com/800/600/homes,restored,1",
                    "https://loremflickr.com/800/600/homes,restored,2",
                    "https://loremflickr.com/800/600/team,response,1",
                    "https://loremflickr.com/800/600/team,response,2",
                    "https://loremflickr.com/800/600/first,aid,1",
                    "https://loremflickr.com/800/600/first,aid,2",
                    "https://loremflickr.com/800/600/community,support,1",
                    "https://loremflickr.com/800/600/community,support,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=W8894gV6ArY",
                    "https://www.youtube.com/watch?v=sb1_vLijK40",
                    "https://www.youtube.com/watch?v=8CQldQfW_oY",
                    "https://www.youtube.com/watch?v=lTMpt8kjbBQ",
                    "https://www.youtube.com/watch?v=m-QsbfsBjk0"
                ],
            },
            {
                "title_en": "Fish Farms Transform Coastal Livelihoods",
                "body_en": "100 fishermen transitioned to sustainable aquaculture. Their income tripled while reducing ocean pressure and creating new jobs.",
                "title_zh_tw": "魚塭改變沿海生計",
                "body_zh_tw": "100名漁民轉向永續水產養殖。他們的收入增加三倍，同時減少了海洋壓力並創造了新工作。",
                "beneficiaries": 100,
                "total_hours_contributed": 280,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": False,
                "cover_image_url": "https://loremflickr.com/800/600/fish,farm,aquaculture",
                "image_urls": [
                    "https://loremflickr.com/800/600/fish,pond,1",
                    "https://loremflickr.com/800/600/fish,pond,2",
                    "https://loremflickr.com/800/600/aquaculture,setup,1",
                    "https://loremflickr.com/800/600/aquaculture,setup,2",
                    "https://loremflickr.com/800/600/fish,monitoring,1",
                    "https://loremflickr.com/800/600/fish,monitoring,2",
                    "https://loremflickr.com/800/600/training,technique,1",
                    "https://loremflickr.com/800/600/training,technique,2",
                    "https://loremflickr.com/800/600/feed,management,1",
                    "https://loremflickr.com/800/600/feed,management,2",
                    "https://loremflickr.com/800/600/harvest,day,1",
                    "https://loremflickr.com/800/600/harvest,day,2",
                    "https://loremflickr.com/800/600/market,sales,1",
                    "https://loremflickr.com/800/600/market,sales,2",
                    "https://loremflickr.com/800/600/coastal,community,1",
                    "https://loremflickr.com/800/600/coastal,community,2",
                    "https://loremflickr.com/800/600/sustainability,practice,1",
                    "https://loremflickr.com/800/600/sustainability,practice,2",
                    "https://loremflickr.com/800/600/income,growth,1",
                    "https://loremflickr.com/800/600/income,growth,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=dIk6V68sBm8",
                    "https://www.youtube.com/watch?v=QKs8bqQ-0Ck",
                    "https://www.youtube.com/watch?v=KWaOjypn3Zo",
                    "https://www.youtube.com/watch?v=1pca674L1OA",
                    "https://www.youtube.com/watch?v=iLN17kZB08U"
                ],
            },
            {
                "title_en": "Blind Students Gain Independence Through Training",
                "body_en": "Our vocational training for 50 blind students resulted in 40 gaining employment. They now support their families with dignity.",
                "title_zh_tw": "盲學生透過培訓獲得獨立",
                "body_zh_tw": "我們為50名盲學生的職業培訓使40人獲得就業機會。他們現在以尊嚴養家。",
                "beneficiaries": 50,
                "total_hours_contributed": 320,
                "published_at": timezone.now(),
                "related_project": None,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/blind,vocational,training",
                "image_urls": [
                    "https://loremflickr.com/800/600/vocational,skills,1",
                    "https://loremflickr.com/800/600/vocational,skills,2",
                    "https://loremflickr.com/800/600/training,support,1",
                    "https://loremflickr.com/800/600/training,support,2",
                    "https://loremflickr.com/800/600/tactile,learning,1",
                    "https://loremflickr.com/800/600/tactile,learning,2",
                    "https://loremflickr.com/800/600/employment,1",
                    "https://loremflickr.com/800/600/employment,2",
                    "https://loremflickr.com/800/600/workplace,accommodation,1",
                    "https://loremflickr.com/800/600/workplace,accommodation,2",
                    "https://loremflickr.com/800/600/mentor,support,1",
                    "https://loremflickr.com/800/600/mentor,support,2",
                    "https://loremflickr.com/800/600/independence,1",
                    "https://loremflickr.com/800/600/independence,2",
                    "https://loremflickr.com/800/600/dignity,work,1",
                    "https://loremflickr.com/800/600/dignity,work,2",
                    "https://loremflickr.com/800/600/success,story,1",
                    "https://loremflickr.com/800/600/success,story,2",
                    "https://loremflickr.com/800/600/family,support,1",
                    "https://loremflickr.com/800/600/family,support,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=rc8W3VHHBE0",
                    "https://www.youtube.com/watch?v=wVwJ1WkhIto",
                    "https://www.youtube.com/watch?v=aI5TYfoE97U",
                    "https://www.youtube.com/watch?v=s2nbu0u57KM",
                    "https://www.youtube.com/watch?v=PF72XUJpjCA"
                ],
            },
            {
                "title_en": "Ancient Weaving Craft Thrives Again",
                "body_en": "120 traditional weavers revived their heritage craft through market training. Their products now sell internationally, generating $50k annually.",
                "title_zh_tw": "古老編織工藝再次興旺",
                "body_zh_tw": "120名傳統編織工人透過市場培訓振興了他們的遺產工藝。他們的產品現在在國際上銷售，每年產生50,000美元。",
                "beneficiaries": 120,
                "total_hours_contributed": 290,
                "published_at": timezone.now(),
                "related_project": related_proj,
                "is_featured": False,
                "cover_image_url": "https://loremflickr.com/800/600/weaving,craft,heritage",
                "image_urls": [
                    "https://loremflickr.com/800/600/loom,weaving,1",
                    "https://loremflickr.com/800/600/loom,weaving,2",
                    "https://loremflickr.com/800/600/traditional,craft,1",
                    "https://loremflickr.com/800/600/traditional,craft,2",
                    "https://loremflickr.com/800/600/artisan,work,1",
                    "https://loremflickr.com/800/600/artisan,work,2",
                    "https://loremflickr.com/800/600/pattern,design,1",
                    "https://loremflickr.com/800/600/pattern,design,2",
                    "https://loremflickr.com/800/600/finished,textile,1",
                    "https://loremflickr.com/800/600/finished,textile,2",
                    "https://loremflickr.com/800/600/market,training,1",
                    "https://loremflickr.com/800/600/market,training,2",
                    "https://loremflickr.com/800/600/product,display,1",
                    "https://loremflickr.com/800/600/product,display,2",
                    "https://loremflickr.com/800/600/export,shipping,1",
                    "https://loremflickr.com/800/600/export,shipping,2",
                    "https://loremflickr.com/800/600/income,increase,1",
                    "https://loremflickr.com/800/600/income,increase,2",
                    "https://loremflickr.com/800/600/artisan,pride,1",
                    "https://loremflickr.com/800/600/artisan,pride,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=cOA8AKv5v6Y",
                    "https://www.youtube.com/watch?v=YjNDBqbRfT0",
                    "https://www.youtube.com/watch?v=f3vVhcZzZv0",
                    "https://www.youtube.com/watch?v=yNN2igIMpsA",
                    "https://www.youtube.com/watch?v=DFXjFwjj4nc"
                ],
            },
            {
                "title_en": "Peace Returns to Conflict Zone",
                "body_en": "After 2 years of mediation training, 30 community leaders successfully resolved 50+ conflicts peacefully within their district.",
                "title_zh_tw": "和平回到衝突區",
                "body_zh_tw": "經過2年的調解培訓，30位社區領袖成功在他們的地區內和平解決了50多起衝突。",
                "beneficiaries": 5000,
                "total_hours_contributed": 450,
                "published_at": timezone.now(),
                "related_project": None,
                "is_featured": True,
                "cover_image_url": "https://loremflickr.com/800/600/peace,reconciliation,community",
                "image_urls": [
                    "https://loremflickr.com/800/600/mediation,training,1",
                    "https://loremflickr.com/800/600/mediation,training,2",
                    "https://loremflickr.com/800/600/dialogue,circle,1",
                    "https://loremflickr.com/800/600/dialogue,circle,2",
                    "https://loremflickr.com/800/600/conflict,resolution,1",
                    "https://loremflickr.com/800/600/conflict,resolution,2",
                    "https://loremflickr.com/800/600/healing,process,1",
                    "https://loremflickr.com/800/600/healing,process,2",
                    "https://loremflickr.com/800/600/community,gathering,1",
                    "https://loremflickr.com/800/600/community,gathering,2",
                    "https://loremflickr.com/800/600/leaders,trained,1",
                    "https://loremflickr.com/800/600/leaders,trained,2",
                    "https://loremflickr.com/800/600/peace,agreement,1",
                    "https://loremflickr.com/800/600/peace,agreement,2",
                    "https://loremflickr.com/800/600/reconciliation,1",
                    "https://loremflickr.com/800/600/reconciliation,2",
                    "https://loremflickr.com/800/600/celebration,peace,1",
                    "https://loremflickr.com/800/600/celebration,peace,2",
                    "https://loremflickr.com/800/600/safe,community,1",
                    "https://loremflickr.com/800/600/safe,community,2",
                ],
                "video_urls": [
                    "https://www.youtube.com/watch?v=SpGKK9t28w0",
                    "https://www.youtube.com/watch?v=Y2bNOiVmWeE",
                    "https://www.youtube.com/watch?v=SzwSCySBmac",
                    "https://www.youtube.com/watch?v=5P73ai8zGpg",
                    "https://www.youtube.com/watch?v=o3fRujnTsGE"
                ],
            }
        ]

        for s_data in stories_data:
            if not SuccessStory.objects.filter(title=s_data['title_en']).exists():
                SuccessStory.objects.create(**s_data)
                self.stdout.write(self.style.SUCCESS(f"Created story: {s_data['title_en']}"))
            else:
                self.stdout.write(f"Story '{s_data['title_en']}' already exists.")