"""
Django settings for gda project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import secrets
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment in production; fall back to a dev key.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    # Use a reasonably long dev key if not provided (not for production use)
    os.environ.get('DJANGO_DEV_SECRET_KEY', 'your-secret-key-here')
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False unless explicitly enabled to avoid accidental production DEBUG=True
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Get allowed hosts from environment or use defaults
ALLOWED_HOSTS = [
    '127.0.0.1','localhost',
    'gda-oy5s.onrender.com',
    'gda-dev.onrender.com',
    'gda-public.vercel.app',
    'gda-public-dev.vercel.app',
]

# CSRF trusted origins for POST requests
CSRF_TRUSTED_ORIGINS = [
    'https://gda-oy5s.onrender.com', # Production instance
    'https://gda-dev.onrender.com', # Development instance
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://gda-public.vercel.app',
    'https://gda-public-dev.vercel.app',
]

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'apps.content',
    'apps.content_management',
    'apps.users',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    'rest_framework',
    'drf_yasg',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'apps.users.middleware.OnboardingMiddleware',
]

ROOT_URLCONF = 'gda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gda.wsgi.application'

ASGI_APPLICATION = 'gda.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('USE_POSTGRES', 'False') == 'True':
    # Using PostgreSQL as the database
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('DB_NAME', 'fallback_db_name'),
            'USER': os.environ.get('DB_USER', 'fallback_db_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'fallback_db_password'),
            'HOST': os.environ.get('DB_HOST', 'fallback_db_host'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # Using dj_database_url to configure the database
    DATABASES = {
        'default': dj_database_url.config(
            default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
            conn_max_age=600
        )
    }  

# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Django Allauth settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth account settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Allow login with either username or email
ACCOUNT_USERNAME_REQUIRED = False # Allow users to sign up without providing a username (one will be generated)
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/300s',  # 5 attempts per 5 minutes
}
ACCOUNT_ADAPTER = 'apps.users.adapters.CustomAccountAdapter'
ACCOUNT_FORMS = {
    'login': 'apps.users.forms.CustomAuthenticationForm',
}

# Login/Logout redirect URLs
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/login/'

# Social account settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'APP': {
            'client_id': os.environ.get('FACEBOOK_CLIENT_ID', ''),
            'secret': os.environ.get('FACEBOOK_CLIENT_SECRET', ''),
        }
    },
    'github': {
        'SCOPE': ['user', 'repo', 'read:org'],
        'APP': {
            'client_id': os.environ.get('GITHUB_CLIENT_ID', ''),
            'secret': os.environ.get('GITHUB_CLIENT_SECRET', ''),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('zh-tw', 'Traditional Chinese'),
]
TIME_ZONE = 'UTC'

USE_I18N = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_TZ = False # True for Use Server time false for Device default time

# Date input formats
DATE_INPUT_FORMATS = [
    '%Y-%m-%d',     # '2006-10-25'
    '%m/%d/%Y',     # '10/25/2006'
    '%m/%d/%y',     # '10/25/06'
    '%b %d %Y',     # 'Oct 25 2006'
    '%b %d, %Y',    # 'Oct 25, 2006'
    '%d %b %Y',     # '25 Oct 2006'
    '%d %b, %Y',    # '25 Oct, 2006'
    '%B %d %Y',     # 'October 25 2006'
    '%B %d, %Y',    # 'October 25, 2006'
    '%d %B %Y',     # '25 October 2006'
    '%d %B, %Y',    # '25 October, 2006'
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# In Docker, STATIC_ROOT should be /app/static (set via env var); locally use 'staticfiles'
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))

# Security-related settings — set via environment in production
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
# HSTS settings (only enable after careful consideration)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'
# If the app is deployed behind a proxy (e.g. Render, Heroku, nginx), the proxy
# usually sets the X-Forwarded-Proto header. In production (DEBUG=False) we
# should trust that header so Django knows requests are secure and builds
# https:// redirect URIs. This prevents redirect_uri_mismatch errors with
# OAuth providers when they expect https:// callbacks.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings for sending emails — prefer environment variables
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 465))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Ensure DEFAULT_FROM_EMAIL is never empty - use a valid fallback
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')
EMAIL_SUBJECT_PREFIX = os.environ.get('EMAIL_SUBJECT_PREFIX', 'GDA ')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 10))